### ISSUE TITLE
Leverage shouldComponentUpdate to improve performance

### ISSUE THREAD

**Issue by bluejamesbond** [rexxars/react-markdown#1]
Just a recommendation :) Additionally, you can process and set innerHTML of the component when source changes.

**Comment by bluejamesbond** [comment]
I have modified your code [here](https://github.com/bluejamesbond/react-markdown/blob/master/src/react-markdown.js) as an example. This should provide considerable performance improvements. Beware. This is a very naive solution however.

**Comment by rexxars** [comment]
I could (and probably will) implement shouldComponentUpdate for the basic props.

The purpose of this library is to use React as much as possible, so manually setting the innerHTML kind of defeats the purpose. There are plenty of other markdown libraries for React that does that, though.
