### ISSUE TITLE
How to add <img> and <blockqoutes> so they render.

### ISSUE THREAD

**Issue by arif-hanif** [rexxars/react-markdown#107]
![image](https://user-images.githubusercontent.com/8672758/33097510-6f565d24-ced8-11e7-9339-78a8627ca566.png)

**Comment by rexxars** [comment]
Set `escapeHtml` to `false`:

```js
<Markdown
  source="# Your markdown here"
  escapeHtml={false}
/>
```

If that doesn't solve your issue, I'm going to need more context. Code sample or similar.
