### ISSUE TITLE
Requiring "commonmark/dist/commonmark" breaks bundling processes

### ISSUE THREAD

**Issue by petetnt** [rexxars/react-markdown#11]
In https://github.com/rexxars/react-markdown/commit/62df2b27b30e22be1e06c90eacc1bb1caac6f80a the Parser require was changed to:

``` diff`
+ var Parser = require('commonmark/dist/commonmark').Parser;
```

This fails at least on Node v4-5, npm@3 and `Browserify` with error

```
>> Error: Cannot find module './common' from 'D:\Projects\crf\node_modules\react-markdown\node_modules\commonmark\dist'
```

There's also an comment from @just-paja in the commit with same happening with `Webpack`

> I like your project, but this breaks webpack for me with a This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results error.

**Comment by rexxars** [comment]
Alright, let me revert this change and release a new version later today. It'll require webpack users to include a JSON-loader, but I feel like this is probably a better option than requiring the dist version here.

**Comment by petetnt** [comment]
:+1:

**Comment by just-paja** [comment]
:+1:

**Comment by rexxars** [comment]
Fixed in new release. Sorry for the wait.

**Comment by petetnt** [comment]
Thanks :+1:
