### ISSUE TITLE
Github flavored markdown, checkboxes not working

### ISSUE THREAD

**Issue by grez72** [rexxars/react-markdown#110]
On github, the following markdown renders checkboxes, but in react-markdown I see bullet points instead. This is also true in the live demo (http://rexxars.github.io/react-markdown/). Is there something else I need to do to render checkboxes?

## TODO

- [ ] task 1
- [ ] task 2

**Comment by rexxars** [comment]
Fixed in v3.1.0, thanks for bringing this to my attention!

**Comment by max-favilli** [comment]
I am using 4.2.2 but doesn't seems fixed:

![image](https://user-images.githubusercontent.com/1472899/69017532-09b16d80-09a8-11ea-9352-8c28a42b7bec.png)


If I inspect the generated html is also weird, adding a `<p>` to the last element:
![image](https://user-images.githubusercontent.com/1472899/69017548-1afa7a00-09a8-11ea-87db-e63f47c7b8e0.png)

Unless an empty line is added after the list like this:
![image](https://user-images.githubusercontent.com/1472899/69017588-539a5380-09a8-11ea-95b0-8564c27548bb.png)

Which prevent the `<p>` from being inserted:
![image](https://user-images.githubusercontent.com/1472899/69017606-6ad94100-09a8-11ea-93b7-6010bf41cfe6.png)

Source:
![image](https://user-images.githubusercontent.com/1472899/69017625-86444c00-09a8-11ea-9fd4-83e5b03c9636.png)
