### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by piotrblasiak** [rexxars/react-markdown#117]
Aren´t linebreaks supposed to be converted into <br>? Any ways to fix this in a nice way?

**Comment by rexxars** [comment]
See https://github.com/rexxars/react-markdown/issues/105#issuecomment-346103734

I'll keep this open as a reminder to add some documentation about it.

**Comment by piotrblasiak** [comment]
Ah, silly me - should have read the spec more carefully. Thanks for clarifying.

**Comment by hayyaun** [comment]
What was the problem? I'm using react-markdown to convert a richtext to HTML. but seems like my \ are not converting to <br />
What's my mistake?
