### ISSUE TITLE
HTML tags displayed in Headers since v3.0.0

### ISSUE THREAD

**Issue by gknapp** [rexxars/react-markdown#119]
Previously anchor tags with `id` attributes were not rendered, they are since v3.0.0:

```
# <a id="trademarks"></a>Trademarks
```
Version 2.5.1:
![v2.5.1](https://user-images.githubusercontent.com/143027/33661347-72a533e4-da7f-11e7-9bd2-b581ee1ed8e5.png)

Version 3.0.0:
![v3.0.0](https://user-images.githubusercontent.com/143027/33661371-86987c58-da7f-11e7-99e5-e6e15fc255e1.png)

**Comment by TheFullResolution** [comment]
*escapeHtml* - boolean Setting to false will cause HTML to be rendered (see note above about broken HTML, though). Be aware that setting this to false might cause security issues if the input is user-generated. Use at your own risk. (default: true).

Set this to false to bring the previous behavior.

**Comment by gknapp** [comment]
Thanks, the source of the markdown is trusted in this instance (it's authored by my employer). I'll upgrade to 3.x and change the setting.
