### ISSUE TITLE
Option for Setting target="_blank" on Links

### ISSUE THREAD

**Issue by Enijar** [rexxars/react-markdown#12]
Is it feasible to allow this as an option for this package?

Something like the following:

```jsx
<ReactMarkdown source={input} linkTargets="_blank"/>
```

**Comment by rexxars** [comment]
A bit unsure. It's easy enough to add, but I don't know if the API makes sense. I think there are two options:

* Allowing users to pass their own handlers for types, eg `Link: MyCustomLinkComponent`. This would be very flexible and is something I've been wanting to add anyway.
* Adding a `linkTarget` prop that can either be a string or a function. The functions could determine the target based on the node, for instance whether it is a relative URL or not.

I'm leaning towards the first, as that will allow all sorts of flexibility to be added without bloating the renderer with options.

**Comment by Enijar** [comment]
I agree. The first option you listed sounds the best way to go and would open up the API to be much more flexible.

Do you have any inkling as to when such a feature could be ready?

**Comment by rexxars** [comment]
I don't think it should be too much work, so it's more a question of when I'll have the time to prioritize it. I'm hoping it'll be this week, at least.

**Comment by Enijar** [comment]
That would be perfect. I really like this package as I don't have to use the `dangerouslySetInnerHTML` property!

Keep up the good work on this package :+1:

**Comment by petetnt** [comment]
Wouldn't the most optimal case be that [any valid attribute](https://facebook.github.io/react/docs/tags-and-attributes.html) would be valid and applied? When rendering the container, you could just spread the props with `...this.props` (and handling special cases such like you do now).

**Comment by rexxars** [comment]
I've implemented custom renderers in `commonmark-react-renderer` (which powers this component). I'll see if I can get a new release of `react-markdown` out quite soon. When that is out it should be as as easy as:
```js
<ReactMarkdown
  source="Click [here](https://espen.codes/) to visit external site"
  renderers={{Link: props => <a href={props.href} target="_blank">{props.children</a>}}
/>
```

**Comment by rexxars** [comment]
Version 4 is now out, and the above example should work for this use case.

**Comment by cyberwombat** [comment]
I wonder how to do a paragraph like this? I end up `Each child in an array or iterator should have a unique "key" prop. Check the render method of 'Paragraph'`

**Comment by elimisteve** [comment]
In case what I found helps others:

I needed something similar within an Electron app and went with [this solution](https://github.com/electron/electron/issues/1344#issuecomment-171516636) before I found this issue:

```
    var shell = require('electron').shell;
    //open links externally by default
    $(document).on('click', 'a[href^="http"]', function(event) {
        event.preventDefault();
        shell.openExternal(this.href);
    });
```

...though this makes _all_ links on the page get opened by the user's default browser, not just links rendered by `react-markdown`, which might not quite be what you're looking for.

**Comment by zoruc** [comment]
shouldn't it be  

`<ReactMarkdown
  source="Click [here](https://espen.codes/) to visit external site"
  renderers={{Link: props => <a href={props.href} target="_blank">{props.children}</a>}}/>`

**Comment by ogtfaber** [comment]
Dont forget to add rel="noopener noreferrer"
(See https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c)

**Comment by goldylucks** [comment]
I'm currently using it like so:
```
    <ReactMarkdown
      renderers={{ Link: (props: Object) => {
        if (props.href.match('http')) {
          return <a href={props.href} target="_blank" rel="nofollow noreferrer noopener">{props.children}</a>
        }
        return <a href={props.href}>{props.children}</a>
      } }}
```

**Comment by gajus** [comment]
Whats the reason you have `if (props.href.match('http')) {` check?

What else can it be?

**Comment by gajus** [comment]
Never mind. Just "realised" that there are a plethora of protocols. That said, I would not recommend blindly constructing a link. A safer option would be:

```js
const renderLink = (props: Object) => {
  if (!props.href.startsWith('http')) {
    return props.children;
  }

  return <a href={props.href} rel='nofollow noreferrer noopener' target='_blank'>{props.children}</a>;
};

```

**Comment by goldylucks** [comment]
@gajus 
that will not work, because `[my internal link](/some-internal-path/)` will just render `my internal link` as text

**Comment by gajus** [comment]
Sorry, this should have been `props.href`, i.e.

```
const renderLink = (props: Object) => {
  if (!props.href.startsWith('http')) {
    return props.href;
  }

  return <a href={props.href} rel='nofollow noreferrer noopener' target='_blank'>{props.children}</a>;
};

```

And yes, that would just render plain text link.

**Comment by goldylucks** [comment]
@gajus 
yes but we want to render an internal link

**Comment by gajus** [comment]
oh, I see. Forgot about that possibility.

**Comment by szeredaiakos** [comment]
having a ```[legitimate link](http://www.example.com//){name:value}``` look easy enough where the {...} is a json with properties added to the link tag. and ignore it if there is a space between ] and { . or maybe go with the ```{:target="_blank"}```

**Comment by CMatias** [comment]
For anyone wondering, in version 4.0.6 the `Link` should be lowercase:

```javascript
<ReactMarkdown 
  source={source}
  renderers={{link: props => <a href={props.href} target="_blank">{props.children}</a>}}
/>
```

**Comment by lebyanelm** [comment]
This has now been changed, renderers attribute is no longer being used. `linkTarget ` is the attribute, with values like `_blank`. More about the APIs can be found in the API Docs `https://github.com/remarkjs/react-markdown#api`.

**Comment by gapon2401** [comment]
Here is how you can add `rel="noopener noreferrer"` for `target="_blank"`:
```
<ReactMarkdown
    linkTarget={'_blank'}
    components={{
        a: ({ node, children, ...props}) => {
            const linkProps = props;
            if (props.target === '_blank') {
                linkProps['rel'] = 'noopener noreferrer';
            }
            return <a {...linkProps}>{children}</a>
        }
    }}
>
```

**Comment by szhu** [comment]
Appreciate all the code snippets everyone's shared above. I wanted to share an improved version that I'm now using, that are more robust than checking whether the URL contains `http` (which fails for links like `/path/containing/http` and `about:blank`):

If you want to check whether the link points to the same domain, regardless of whether it's an absolute URL or not:

```jsx
<ReactMarkdown
  components={{
    a({ node, children, ...props }) {
      let url = new URL(props.href ?? "", location.href);
      if (url.origin !== location.origin) {
        props.target = "_blank";
        props.rel = "noopener noreferrer";
      }

      return <a {...props}>{children}</a>;
    },
  }}
>
  {`[External Link](https://example.com)\n\n[Internal Link](#anchor)`}
</ReactMarkdown>
```

If you just want to check whether the link is an absolute URL:

```jsx
<ReactMarkdown
  components={{
    a({ node, children, ...props }) {
      try {
        new URL(props.href ?? "");
        // If we don't get an error, then it's an absolute URL.

        props.target = "_blank";
        props.rel = "noopener noreferrer";
      } catch (e) {}

      return <a {...props}>{children}</a>;
    },
  }}
>
  {`[External Link](https://example.com)\n\n[Internal Link](#anchor)`}
</ReactMarkdown>
```
