### ISSUE TITLE
Clicking checkboxes

### ISSUE THREAD

**Issue by philraj** [rexxars/react-markdown#120]
Hi,

If I use source like `- [ ] checkbox` and click on the checkbox, this warning is displayed:
```
Warning: Failed prop type: You provided a `checked` prop to a form field without an
`onChange` handler. This will render a read-only field. If the field should be mutable
use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by ListItem)
```
It would be interesting to provide some way to actually handle the state changes other than changing the markdown source itself, but it sounds like a lot of work to handle the fact that the structure of the checkbox inputs is completely dynamic depending on the source. So it might be a good idea to make checkbox inputs `readOnly` by default to at least suppress the warning and make the behavior clear.

**Comment by rexxars** [comment]
Good point. Would you care to send a pull request?
Relevant code: https://github.com/rexxars/react-markdown/blob/master/src/renderers.js#L68
+ tests probably will need to update some snapshots

**Comment by philraj** [comment]
Sure, should I commit the generated `demo.js` file?

**Comment by rexxars** [comment]
Yes, please

**Comment by philraj** [comment]
Here you go: https://github.com/rexxars/react-markdown/pull/121

**Comment by rexxars** [comment]
Thanks chief! Will push out a new release in a bit
