### ISSUE TITLE
Allow links to be opened in a new window/tab

### ISSUE THREAD

**Issue by chrisjpatty** [rexxars/react-markdown#122]
First of all, love this package. Thanks so much for all the hard work your team has put in to making such a great drop-in plugin for markdown. I have a use-case where it would be really nice to be able to change the  `target` property of the generated `<a/>` tag for links. As far as I can tell, there's nothing in the Markdown spec to support this, so enabling it would require deciding on a syntax to do so. My thought is to allow a third square bracket after the link title and URL with a string defining the target. If this sounds like an acceptable proposal I would be happy to help contribute to make it happen.

**Comment by rexxars** [comment]
Thanks!

I'd rather not add any new syntax to markdown. You can use a custom renderer for the `link` node type and add a `target` property based on the `href` or similar.
