### ISSUE TITLE
Feature request: Add a `commonmark` option

### ISSUE THREAD

**Issue by a-ignatov-parc** [rexxars/react-markdown#129]
It seams that `react-markdown` staring from `3.0.0` isn't commonmark compliant any more because `commonmark` option is disabled by default in `remark-parse`. It's more breaking than public api changes and there is no notes about it. This was done on purpose?

**Comment by rexxars** [comment]
Yes. I got so many requests for tables and other non-commonmark features that I decided to switch. I could enable the commonmark option, but I'd have to make sure documentation clearly stated that certain features simply won't work in that mode.

**Comment by a-ignatov-parc** [comment]
I understand. And want to clarify that Commonmark spec allow adding any extensions we want (like tables). It's main goal is to make parsing more deterministic by strict syntax.

There is even list with [proposed extensions](https://github.com/commonmark/CommonMark/wiki/Proposed-Extensions). 

Also github made there flavors upon commonmark spec. So I think it's a good idea to continue using commonmark ;)

**Comment by a-ignatov-parc** [comment]
At least we should have ability to pass `commonmark` option to `remark-parse`. I'd say it should be turned on by default but that would breaking change to `v3` and backward compatible to `v2` 🤔

**Comment by rexxars** [comment]
I'd be open for adding the option. I don't want to enable it by default - I think that will lead to more support issues rather than less (though I appreciate a stricter format on a *personal* level).

**Comment by a-ignatov-parc** [comment]
Not going to argue 👍 

But please mention in Readme that `react-markdown@3` isn't commonmark compliant by default. This could be a big surprise for v2 users.

**Comment by a-ignatov-parc** [comment]
Also it would be good to point that `remark-parse` has [some inconsistency](https://github.com/remarkjs/remark/issues/306) with commonmark spec.

**Comment by rexxars** [comment]
This is now (kind of) possible by using the  `parserOptions` feature in v4.1.0:
```
<ReactMarkdown source="# yer markdown" parserOptions={{commonmark: true}} />
```
