### ISSUE TITLE
my component how to work

### ISSUE THREAD

**Issue by ismumu** [rexxars/react-markdown#133]
![2018-01-05 16 28 38](https://user-images.githubusercontent.com/8435569/34601118-84b0dcf0-f235-11e7-8c41-974cd9d7bd7a.png)

the  component SyntaxHighlighter  not work....

**Comment by rexxars** [comment]
You specify a custom renderer for the `code` node type.

Something along the lines of:

```js
<ReactMarkdown
  source={textContent}
  renderers={{
    code: props => (
      <SyntaxHighlighter language={props.language}>
        {props.value}
      </SyntaxHighlighter>
    )
  }}
/>
```
