### ISSUE TITLE
Can't render full <pre> container if there are blank lines?

### ISSUE THREAD

**Issue by geotrev** [rexxars/react-markdown#136]
Hola folks,

Something I noticed while trying to render some markdown files in my project.  Let's say I have this markdown wrapped with the regular backticks to create a pre element:

```
<backticks>js
some stuff here

more stuff here
</backticks>
```
(ignore the `<backticks>`, just pretend those are ` ``` `)

Notice how there's a space between lines there? It ends up rendering this HTML:

```
<pre>some stuff here</pre>

<p>more stuff here</p>
```

Why doesn't it completely wrap the text in `<pre>`? Is this intentional? Thanks!

**Comment by rexxars** [comment]
I can't reproduce this. Tried in [the demo](https://rexxars.github.io/react-markdown/), both with and without a custom code renderer. Both renders a plain `<pre>` with newline characters - no paragraphs.

Please provide a reproducible test case and I will investigate further.
