### ISSUE TITLE
Can it be used with React Native?

### ISSUE THREAD

**Issue by cutoz** [rexxars/react-markdown#141]

**Comment by rexxars** [comment]
I have not given it a try, but with #140 being merged I think it should be possible by specifying custom renderers. Is there a package.json `browser` alternative for react native? If so, we could probably create a separate set of renderers for react native and ship them by default, which would be pretty nice.

**Comment by Taym95** [comment]
Use this https://github.com/Benjamin-Dobell/react-native-markdown-view

**Comment by cutoz** [comment]
OH, great thanks.

**Comment by edward1127** [comment]
has anyone successfully used it in native?

**Comment by ChristianMurphy** [comment]
This issue is five years and several major versions outdated.
You can see more recent discussion at https://github.com/orgs/remarkjs/discussions/1183

I'm locking this issue as it is no longer a good source of information.
