### ISSUE TITLE
React Unique Key Warning when overriding the default text renderer

### ISSUE THREAD

**Issue by vanchagreen** [rexxars/react-markdown#145]
If you override the default text renderer with a function that returns a React Element, it doesn't have access to the key that every other node gets.

And if you don't pass in a key to your new React Element, you'll potentially get the warning.

I have a fix out for this problem in this PR here (as well as a README change) here: https://github.com/rexxars/react-markdown/pull/144

Thanks!

**Comment by rexxars** [comment]
Thanks for reporting, and even bigger thanks for the PR :)

**Comment by rexxars** [comment]
Fixed in v3.2.1
