### ISSUE TITLE
Missing horizontal rule <hr /> with "---" markdown

### ISSUE THREAD

**Issue by mrigo** [rexxars/react-markdown#147]
Hi!
Is it possible to to render a `<hr />` element?

In markdown syntax I think it's "---" and the render is like this

---

And under a text is like this
---

Thanks!
\m

**Comment by rexxars** [comment]
Sure, you can use `---` or `***`. Just make sure there are empty lines before/after them.
Text with `---` directly under it transforms the text to a heading.

There's even a horizontal rule in the demo, near the end:
https://rexxars.github.io/react-markdown/
