### ISSUE TITLE
link renderer skips referenced Markdown links

### ISSUE THREAD

**Issue by joshkadis** [rexxars/react-markdown#148]
Using the `renderers` option works great, except that it skips links where the `href` if referenced at the end of the document.

```
[this link works great!](https://example.com)

[this link is skipped][1]
...
[1]: https://example.com
```

Also worth noting that the `href` is URL encoded in the second example but not in the first.

**Comment by rexxars** [comment]
There is a separate `linkReference` renderer. Can you ellaborate on the URL-encoding issue?

**Comment by joshkadis** [comment]
Ah, thanks. I couldn't reproduce the URL encoding, will try to remember how I messed it up in the first place. This is what I got:

```
<Markdown
  source="[link](https://example.com?{hello,world})"
/>
<Markdown
  source={`[link reference][1]
[1]: https://example.com?{hello,world}`}
/>
...
<div><p><a href="https://example.com?{hello,world}">link</a></p></div>
<div><p><a href="https://example.com?{hello,world}">link reference</a></div>
```
I guess it makes sense that you leave encoding up to the user, carry on...

Thanks!
