### ISSUE TITLE
Support React.Fragment as a renderer

### ISSUE THREAD

**Issue by bsonntag** [rexxars/react-markdown#149]
I tried using [React.Fragment](https://reactjs.org/docs/fragments.html) as the `root` renderer and I got the following error:

```
Error: Renderer for type `root` not defined or is not renderable`
```

This happened because `React.Fragment` is neither a function nor a string (it's actually a symbol), so it fails [this test](https://github.com/rexxars/react-markdown/blob/master/src/ast-to-react.js#L16).

**Comment by rexxars** [comment]
It should work fine if you pass a function that _renders_ using a fragment, though:
```js
const input = '# Header\n\nfoo'
const root = props => (
  <React.Fragment>
    {props.children}
    <span>And that is the end of that</span>
  </React.Fragment>
)

ReactDOM.render(
  <Markdown source={input} renderers={{root}} />,
  document.getElementById('someElement')
)
```

I think perhaps we should consider transitioning to using fragment by default, but it's a breaking change (root class won't get applied), so I think it'll have to wait until the next major, for now.

**Comment by rexxars** [comment]
Let me know if this doesn't solve your issue, and I'll revisit :)

**Comment by bsonntag** [comment]
> It should work fine if you pass a function that renders using a fragment

Yes, that works, but couldn't this be done with `React.Fragment && React.Fragment === renderer`?
I can submit a PR with that.

> I think perhaps we should consider transitioning to using fragment by default

That means dropping support for React < 16.2.0.

**Comment by rexxars** [comment]
Sure,  I'd love a pr for this. As for the react support, I suppose one could check if React.Fragment is defined before using it to maintain support for older versions, but it might be a little confusing to have a container element in one case and not in the other, so I suppose it makes sense to just continue as-is.
