### ISSUE TITLE
Undocumented `plugins` prop

### ISSUE THREAD

**Issue by jjenzz** [rexxars/react-markdown#151]
I wanted to provide styling for `<kbd />` elements and came across the `plugins` prop in source which allows me to pass additional `unified` parser plugins. It has allowed me to use [`remark-kbd`](https://www.npmjs.com/package/remark-kbd) and provide my own custom `kbd` renderer but I'm a bit nervous about using an undocumented prop. 

Is it intentionally undocumented or am I safe to use it and provide a PR to document it?

**Comment by rexxars** [comment]
It was a bit experimental. I've found it hard to communicate which plugins are supported and which are not, since we can only use parser plugins. I'd be happy to accept a PR documenting, if we can find a way to explain it properly.

**Comment by jjenzz** [comment]
Would the following suffice for now?

- `plugins` - _array_ An array of [remark](https://github.com/remarkjs/remark) parser plugins  (default: `[]`)

**Comment by rexxars** [comment]
Hey, sorry for the late answer. Yeah, for now that should be good enough :)

**Comment by jonheslop** [comment]
Hello, I’ve been having ago with the `plugins` prop trying to setup a renderer for shortcodes using [remark-shortcodes](https://github.com/djm/remark-shortcodes). 

A shortcode of `[[ tweet id="67" ]]` will return 
```json
{type: "shortcode", identifier: "tweet", attributes: {id: "67"}}
```
It only passes `children: undefined` as props and not `identifier` or `attributes` so I can’t do anything useful with the shortcode?

I know you said that `plugins` is experimental so perhaps I shouldn’t be shocked.

Any pointers would be greatly appreciated

**Comment by rexxars** [comment]
Added some documentation in 320c22b150516306ce70e31e8bd16e6bf365f073
