### ISSUE TITLE
Documentation mode raw

### ISSUE THREAD

**Issue by hendrixroa** [rexxars/react-markdown#154]
Hi everyone, this component its amazing, but i need know how set a props for render markdwon in mode raw. 
Regards.

**Comment by rexxars** [comment]
What do you mean by "raw"?

**Comment by rexxars** [comment]
If you are thinking about the `raw` html mode shown in the demo, that is the default mode ( `escapeHtml: false`, `skipHtml: false`).

**Comment by hendrixroa** [comment]
Oh thanks!
