### ISSUE TITLE
Nesting an unordered list in an ordered list doesn't work

### ISSUE THREAD

**Issue by chris-pearce** [rexxars/react-markdown#155]
When doing this in the [editor](https://rexxars.github.io/react-markdown/):

```markdown
1. Number 1
2. Number 2
  * Number 4
  * Number 5
```

The nested `<ul>` isn't nested within the `<ol>`, instead it's a sibling in the HTML:

<img width="175" alt="screen shot 2018-03-19 at 11 22 27 am" src="https://user-images.githubusercontent.com/1342772/37573067-d789460e-2b67-11e8-8a2f-fb82f01d3e4d.png">

How it renders:

<img width="141" alt="screen shot 2018-03-19 at 11 21 17 am" src="https://user-images.githubusercontent.com/1342772/37573071-ddc26f50-2b67-11e8-9dc2-33674ecfe445.png">

**Comment by chris-pearce** [comment]
Actually nested only ordered lists aren't working for me either. E.g.:

```markdown
1. Aenean rutrum augue in dictum tempus
2. Lorem ipsum dolor sit amet
  1. Cras sed metus ut orci sodales fringilla
    1. Sed vehicula scelerisque augue
    2. Facilisis in pretium nisl aliquet
    3. Nulla volutpat aliquam velit
  2. Lorem ipsum dolor sit amet
3. Nam lacinia mauris in sollicitudin ornare
4. Quisque eu nunc ac elit maximus efficitur
```

The HTML:

<img width="515" alt="screen shot 2018-03-19 at 12 07 09 pm" src="https://user-images.githubusercontent.com/1342772/37573630-1d48164c-2b6e-11e8-815e-a111168babe0.png">

How it renders:

<img width="352" alt="screen shot 2018-03-19 at 12 08 34 pm" src="https://user-images.githubusercontent.com/1342772/37573645-4aa8e602-2b6e-11e8-9fc6-6be34314dc6f.png">

**Comment by rexxars** [comment]
Use more spaces :)

The commonmark specification (as well as most markdown "specifications") says to use 4 spaces to signify a parent->child relationship. For instance, this is the example markdown you pasted:

```md
1. Number 1
2. Number 2
  * Number 4
  * Number 5
```

And this is how GitHub renders that:

1. Number 1
2. Number 2
  * Number 4
  * Number 5

**Comment by chris-pearce** [comment]
OK my bad, should have picked up on that.

**Comment by bz-stripe** [comment]
Does this work with 8 spaces to denote a nested list in a nest list item?

**Comment by rishadbaniya** [comment]
So i was having same issue, where i spent whole day figuring out what went wrong despite of using the library correctly and following the proper syntax of markdown.

I had global selector as 
```
*{
margin : 0px;
padding : 0px;
box-sizing : border-box;
}
```
If above solutions don't work, then please give this solution a go by removing the ```margin : 0px``` in any global selectors
