### ISSUE TITLE
HTML tags are not working

### ISSUE THREAD

**Issue by atharvajava** [rexxars/react-markdown#157]
` const input=`# ${this.state.title} \n\n ${this.state.body}`; // this is how i am passing the input `

I am not sure if this is how it works as this is the first time i am trying to use this library.  Markdown seems to work all fine but then again I cannot do something like #Hello #Hello the prior works but the former is not marked

**Comment by rexxars** [comment]
Sorry, I don't understand what you mean by this :/
Feel free to reopen with more details if this is still an issue. Please also read this note on inline HTML not being fully implemented/working: https://github.com/rexxars/react-markdown#inline-html-is-broken
