### ISSUE TITLE
<ul> last <li> is not appending <p> tag

### ISSUE THREAD

**Issue by PrudviGali** [rexxars/react-markdown#158]
`ul` element last `li` tag is not appending `p` tag to it.

Steps to reproduce:
[Go to this link](https://rexxars.github.io/react-markdown/)

Please the below markup and open the dev tools to check the HTML. Last <li> should have <p> inside it like others <li> elements. But it missing at this moment. 

-   Test1

-   Test2

-   Test3

Expected behavior: 
```<ul>
<li>
<p><!-- react-text: 612 -->Test1<!-- /react-text --></p>
</li>
<li>
<p><!-- react-text: 635 -->Test2<!-- /react-text --></p>
</li>
<li>
<p><!-- react-text: 670 -->Test3<!-- /react-text --></p>
</li>
</ul>



Current behavior:

<ul>
<li>
<p><!-- react-text: 612 -->Test1<!-- /react-text --></p>
</li>
<li>
<p><!-- react-text: 635 -->Test2<!-- /react-text --></p>
</li>
<li><!-- react-text: 670 -->Test3<!-- /react-text -->
</li>
</ul>

**Comment by peckykom** [comment]
Why it does´t work without <p>?
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
</ul>

I create some solution which render each <li> separate in <ul>, but it isn´t good.
<ul>
<li>a</li>
<ul>

<ul>
<li>b</li>
<ul>

**Comment by peckykom** [comment]
Why it doesn´t work without `<p>`?
`<ul>`
`<li>a</li>`
`<li>b</li>`
`<li>c</li>`
`<ul>`

I create some solution where each `<li>` is in new `<ul>`, but is not good:

`<ul>`
`<li>a</li>`
`<ul>`

`<ul>`
`<li>b</li>`
`<ul>`

`<ul>`
`<li>c</li>`
`<ul>`

**Comment by PrudviGali** [comment]
We have some styles over '<p>' tag, which was not applied to children of the last li.

**Comment by ReneF1** [comment]
I encounter the same error, but instead `<p>` is applied to the last `<li>` element where it shouldnt. Any idea how to get a clean list structure ?

**Comment by jmoseley** [comment]
I'll take a stab at this.

**Comment by rexxars** [comment]
Fixed in v4.1.3

**Comment by djibarian** [comment]
Why is a `p` tag injected inside an `li`?

Can be that disabled in any way to produce:

```
<ul>
  <li>line 1</li>
  <li>line 2</li>
</ul>
```

instead of

```
<ul>
  <li><p>line 1</p></li>
  <li><p>line 2</p></li>
</ul>
```

**Comment by wooorm** [comment]
Because that is how markdown works. See the spec: https://commonmark.org.
If you use tight lists, you don’t get `<p>`s:
```markdown
* a
* b
```
If you use loose lists, you do get `<p>`s:
```markdown
* a

* b
```

Locking because it’s bad practise to comment on ancient, solved, issues.
