### ISSUE TITLE
Can't get renderers to work

### ISSUE THREAD

**Issue by mkpietrzyk** [rexxars/react-markdown#167]
Hello! The markdown support is great... however I can't help it in terms of rendering through renderers.

Below screenshots estimates my current output:

<img width="856" alt="zrzut ekranu 2018-04-18 o 16 31 56 3" src="https://user-images.githubusercontent.com/23457146/38938659-5990b62a-4326-11e8-9057-ddef1584bf6f.png">
<img width="538" alt="zrzut ekranu 2018-04-18 o 16 32 00 3" src="https://user-images.githubusercontent.com/23457146/38938660-59ac72a2-4326-11e8-869c-bc1da050e456.png">

I am getting the text from specific MD file, which is parsed and thrown into React Markdown.. everything works fine except the fact that rowRenderer does not render anything I want it to do so. It does not even get inside the renderer. 

What am I doing wrong? I tried props.value, tried props, tried anything. Maybe it's just so simple I have ommited it. 

Thanks. 

EDIT: I have also tried your solution with CodeBlock for rendering.. does not work as well..

**Comment by rexxars** [comment]
Works just fine here...

```js
import React, { Component } from 'react'
import ReactMarkdown from 'react-markdown'

const source = `
Foo \`console.log('foo')\` baz

| foo | bar |
|-----|-----|
| bar | baz |

\`\`\`js
const foo = "bar"
\`\`\`
`

const inlineCode = props => <strong>{props.value}</strong>
const code = props => <pre><code>{props.value}</code></pre>
const tableRow = props => <tr className="foo">{props.children}</tr>

class App extends Component {
  render() {
    return (
      <div className="App">
        <ReactMarkdown source={source} renderers={{code, inlineCode, tableRow}} />
      </div>
    );
  }
}

export default App

```

**Comment by rexxars** [comment]
What is the value of the `source`?

**Comment by mkpietrzyk** [comment]
I don't have access to the code but from what I remember it's a md file parsed to html as string. Something like "<H1>something</H1>... {...}"

**Comment by mkpietrzyk** [comment]
Im sorry it automatically translated to markdown but you get the idea I hope

**Comment by rexxars** [comment]
Not sure I do... The whole point of this library is to convert markdown to react/html. If it's already HTML, it really doesn't make any sense.

**Comment by mkpietrzyk** [comment]
Okay I know what happened. Currently I have used special loader plugin to load markdown files ( Our project is not using webpack) ... turns out it already converts markdown to html.

So I installed another plugin which transforms md to string and now it works properly :) I could use the first one but yours allows me to make more content rendering configuration :) 

I think I just made myself an idiot 👍 Thanks and my apologies :)

**Comment by rexxars** [comment]
No worries, glad you figured it out :)
