### ISSUE TITLE
How to use program code to remove ">" spaces

### ISSUE THREAD

**Issue by god-david** [rexxars/react-markdown#168]
Today encountered a problem, come and ask everyone：
When there is a space, markdown can't parse the content after the space. I want to express the meaning of how to remove the ">" space before the content so that the contents after ">" can be displayed normally in the format of markdown. Thank you ～We are expecting a reply

The following is a markdown format with a space that does not display properly:

---------------------------------------------

>error markdown format:

* **language expression	**

        > * Puzzle quiz: ** must be taken every year **, usually let the child guess some common
        > * Read short passage: 2016 and 2015** have been tested for two consecutive years
        > * Telling stories/watching words: ** Only ** has been tested in 2012;
        > * Reading children's songs: ** Only ** were tested in 2011.

* **English**

        > * English retelling/follow-up: ** must be taken every year **, generally in a form
        > * English Q&A: What color? And other simple questions.

---------------------------------------------

> correct markdown format:

* **language expression	**

> * Puzzle quiz: ** must be taken every year **, usually let the child guess some common
> * Read short passage: 2016 and 2015** have been tested for two consecutive years
> * Telling stories/watching words: ** Only ** has been tested in 2012;
> * Reading children's songs: ** Only ** were tested in 2011.

**Comment by rexxars** [comment]
I'm sorry, I don't understand.
Could you post a [gist](https://gist.github.com/) with the input and _expected_ output?

**Comment by rexxars** [comment]
Feel free to reopen if still an issue.
