### ISSUE TITLE
Support for <kbd>

### ISSUE THREAD

**Issue by kadishmal** [rexxars/react-markdown#17]
Perhaps this can be fixed together with #16. Basically, our content includes `<kbd>Enter</kbd>` like text to render a keyboard hotkeys like <kbd>Enter</kbd>. There is a CSS defined for it. However, `react-markdown` renders it into:

```
<span><kbd></kbd></span><span>Enter</span>
```

**Comment by rexxars** [comment]
The new release candidate for v3 has (very basic) support for attributeless, inline html nodes, which will allow this to work. Please read this issue for more information. Please give it a go and let me know if you encounter issues.
