### ISSUE TITLE
cdnjs copy exports a camel-cased reactMarkdown instead of ReactMarkdown

### ISSUE THREAD

**Issue by thedustyrover** [rexxars/react-markdown#171]
This might be a bit outside the domain of this project, but I was noticing that the cdnjs exports a camelCased `reactMarkdown`. This won't render (as React expects all classes to be fully capitalized, and treats it as a literal html `<reactMarkdown />` instead.

https://cdnjs.cloudflare.com/ajax/libs/react-markdown/3.3.2/react-markdown.js

One workaround currently is that a constant for the fully capitalized can be set:

    const ReactMarkdown = reactMarkdown;

**Comment by rexxars** [comment]
Thanks for pointing this out and sorry for the late reply. I want to fix this, but I think this would cause a breaking change and would require a major version bump. I'll schedule this for 4.0.

**Comment by rexxars** [comment]
Fixed in 88d12c7a96bcd59640a68d9c16e00adde058c51b
