### ISSUE TITLE
drop xtend dependency

### ISSUE THREAD

**Issue by misantronic** [rexxars/react-markdown#175]
As far as I see it, `xtend` does the same job as the browsers' native `Obejct.assign` and is therefore obsolete as a dependency.
If there is no obvious reason, I might send a PR and drop the `xtend`- dependency.

**Comment by rexxars** [comment]
`Object.assign` is not supported in Internet Explorer, unfortunately. I'd like to keep browser support in line with React, which supports IE9 and up (given you polyfill Map, Set and requestAnimationFrame)

**Comment by jimmywarting** [comment]
Then i think a polyfill for object.assing should be used instead, then better browser would be able to garbe collect the things it don't need

**Comment by rexxars** [comment]
`xtend` is already being used by upstream dependency remark-parse and the like, so changing to a different polyfill would actually _add_ to the size of the bundle instead of reducing the size.
