### ISSUE TITLE
How can I set the tab size

### ISSUE THREAD

**Issue by Liaozhenting** [rexxars/react-markdown#178]
The default option is 1 key tab is equal to 8 key space.
I hope 1 key tab is equal to 4 key space.
![test1](https://user-images.githubusercontent.com/20339251/40696662-53f0d044-63f9-11e8-8e08-a772cab642cc.PNG)

![test2](https://user-images.githubusercontent.com/20339251/40696670-5b973af4-63f9-11e8-843c-738e9954f749.PNG)

I try to set tabSize , but it did not works.

**Comment by rexxars** [comment]
I don't see how this is related to react-markdown, code blocks are treated as-is, wrapped in `<pre>`
