### ISSUE TITLE
Having trouble get plugins working

### ISSUE THREAD

**Issue by dekryptic** [rexxars/react-markdown#179]
Here's my attempt: https://codesandbox.io/s/9zo29v9k5o

**Comment by dekryptic** [comment]
Turns out it was an issue with remark-shortcodes version 0.2.0.

**Comment by gnuletik** [comment]
Did you succeed to make it work ? It seems that even with the previous version, the demo is not working.

**Comment by gnuletik** [comment]
Oh my bad, this is just the `<` characters in the plugin configuration which are in the wrong order.
