### ISSUE TITLE
Render blows up if given slightly invalid markdown

### ISSUE THREAD

**Issue by nwwells** [rexxars/react-markdown#18]
Not sure what, if anything, I'm doing wrong here. This is all I'm specifying:

```
<Markdown escapeHtml={true} source={"Hello \n---\n**World**!"}/>
```

and I'm getting in the console:

```
Uncaught TypeError: Can't add property context, object is not extensible
```

If I add 2 `\n` between the `---` and the rest, then it's not a problem.

**Comment by rexxars** [comment]
Can't reproduce. Which version of React are you using?

**Comment by nwwells** [comment]
Was on `react@0.13.3`. I'm in the process of upgrading to `react@0.14.7` and the problem doesn't exist for some reason with this version.

**Comment by rexxars** [comment]
Thanks to  checking!
