### ISSUE TITLE
`\n` alone is not rendered but seems skipped

### ISSUE THREAD

**Issue by CPatchane** [rexxars/react-markdown#180]
Hi here,

I don't know if it is an issue or an expected behaviour but I explain my case.

If I use two `\n` consecutively: `Here is a text.\n\nHere is another text.`, it will be rendered as two parts as expected: `<p>Here is a text.</p><p>Here is another text.</p>`

But I have a "weird" behaviour, when I test with this text: `Here is a text.\nHere is another text.`. I got all wrapped in a `</p>` like: `<p>Here is a text. Here is another text.</p>` (the `\n` is replaced by a space).

I think the expected render should be replacing `\n` by a `<br/>`, what do you think?

**Comment by rexxars** [comment]
No, this is the expected behavior in markdown. If you want to force newlines, use two spaces before the newline character. See http://markdown-guide.readthedocs.io/en/latest/basics.html#line-return

**Comment by CPatchane** [comment]
Ok this two spaces with a `\n`. Thanks for the quick response @rexxars 👍

**Comment by gocreating** [comment]
The input source
```
a\s\s
\s\s
a
```
is rendered as
```
<p>a</p>
<p>a</p>
```
instead of
```
<p>a</p>
<p></p>
<p>a</p>
```

Is this how markdown behaves?

**Comment by rexxars** [comment]
Working as intended.
