### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by petrgazarov** [rexxars/react-markdown#181]
Having this error thrown at times, specifically when source is html such as `<p>something</p>`.

```
ast-to-react.js:10 Uncaught TypeError: Cannot read property 'type' of undefined
    at astToReact (ast-to-react.js:10)
    at ast-to-react.js:29
    at Array.map (<anonymous>)
    at resolveChildren (ast-to-react.js:28)
    at astToReact (ast-to-react.js:25)
    at ReactMarkdown (react-markdown.js:42)
    at ReactCompositeComponent.js:306
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:305)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:280)
```

Config:
```
  const allowedMarkdownTypes = [
    'paragraph',
    'emphasis',
  ];

  <ReactMarkdown
    source={source}
    allowedTypes={allowedMarkdownTypes}
    unwrapDisallowed={true}
    renderers={{image: ImageRenderer, link: LinkRenderer}}
  />
```

Adding `'html'` to `allowedTypes` seems to fix the problem. I don't want to allow `html` but I guess I have to add this type to avoid the error. Not sure if adding this type has any side effects (right now, the html is escaped and is not rendered anyway).

***

react-markdown version `3.3.2`
react version `15.4.2`
node version `8.9.0`

**Comment by petrgazarov** [comment]
There are other source values that cause this error. Several examples that I found, there may be more that I didn't find:

`***`

`![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")`

**Comment by petrgazarov** [comment]
Sent a PR with a fix, seems to work for my purposes

https://github.com/rexxars/react-markdown/pull/182

**Comment by mrovinsky** [comment]
I get the same error with the last version of `react-markdown`

**Comment by ChristianMurphy** [comment]
@mrovinsky please share a reproduction of the problem you are seeing in a new issue.
Rather than commenting on a likely unrelated issue which was fixed four years ago, thanks.
