### ISSUE TITLE
Markdown links wrapped with brackets are not rendered properly

### ISSUE THREAD

**Issue by bw** [rexxars/react-markdown#186]
I'm not sure what the best solution is, but we use ReactMarkdown to render emails that have been converted to Markdown.

As email clients will often add brackets `<>` around email addresses in replies and forwards, this breaks ReactMarkdown. In particular, I think this behavior causes ReactMarkdown to see it as a node and not just a piece of text:

```
From: **Example From** <[MyEmail@test.com](mailto:MyEmail@test.com)>  
Date: Sat, Jan 20, 2018 at 10:36 AM  
...
```

What's supposed to happen:

```
From: <strong>Example From</strong>
&lt;<a href="mailto:MyEmail@test.com">MyEmail@test.com</a>&gt;<br />
```

What actually happens:

```
From: <strong>Example From</strong>
<a href="mailto:MyEmail@test.com">[MyEmail@test.com](mailto:MyEmail@test.com)</a><br />

// Looks like: [MyEmail@test.com](mailto:MyEmail@test.com)
// And not: MyEmail@test.com
```

Is there a way we can handle this scenario? I know it's a bit of an edge case.

**Comment by rexxars** [comment]
Sorry, you'll have to file an issue with [remark-parse](https://github.com/remarkjs/remark/issues) for this one
