### ISSUE TITLE
allowedTypes has some params in the doc but `text` is missing

### ISSUE THREAD

**Issue by jeff-studionone** [rexxars/react-markdown#187]
Hey, guys, I want to use `text` but I got an error and I noticed that value is not anymore in your core. it could be a bug in the doc or in your code. 

https://github.com/rexxars/react-markdown/blob/74787498e370adf71fe97d91e50a0ce32fc4e6eb/src/renderers.js#L8

**Comment by ekilah** [comment]
i'm not familiar with the source code but the `text` renderer passes a string and expects either a string or ReactElement returned, I had an error as well because there is no default `text` renderer

**Comment by rexxars** [comment]
Note: This changed in 4.0. `text` is now a renderer and gets a `props` object with `children` set to the text value. `text` now also needs to be included in the `allowedTypes` array to be rendered.
