### ISSUE TITLE
suggest: support table

### ISSUE THREAD

**Issue by sinkcup** [rexxars/react-markdown#19]
suggest: support GFM(GitHub flavored markdown) tables: https://help.github.com/articles/organizing-information-with-tables/

```
| Command | Description |
| --- | --- |
| `git status` | List all *new or modified* files |
| `git diff` | Show file differences that **haven't been** staged |
```

**Comment by ztratar** [comment]
These are pretty important. Would love to see!

**Comment by rexxars** [comment]
I'd love to support them, but commonmark does not include them in the spec. I'm going to start experimenting with an alternative markdown parser. It might take a while to complete, since it'll almost be a complete rewrite, however.

**Comment by aviadl** [comment]
+1
Can you please share the status on this ?

**Comment by rexxars** [comment]
Have no gotten much farther on this. Have experimented with alternative markdown parsers, and know that it's doable, it's just a matter of getting time to do it. Right now other projects are taking up most of my time. Don't want to give out estimates for open-source work as it totally depends on how much free time I have to work on it, which varies.

**Comment by TakanashiOuken** [comment]
+1 For this
Really need the table working

**Comment by sauravskumar** [comment]
+1 for table... really need it...

**Comment by sauravskumar** [comment]
https://github.com/chjj/marked     this markdown parser has support for tables...

**Comment by Swivelgames** [comment]
This was pretty damn awesome until I almost finished what I was working on, tried to use a table, and it fell flat on its face 😢 

Switched over to [`remarkable`](https://www.npmjs.com/package/remarkable) and [`highlight.js`](https://www.npmjs.com/package/highlight.js) as seen in [Facebook's own Markdown React example](https://facebook.github.io/react/docs/tutorial.html#adding-markdown).

**Comment by sasha240100** [comment]
+1 For tables

**Comment by tuchk4** [comment]
https://github.com/tuchk4/storybook-readme/issues/4

**Comment by rexxars** [comment]
Just thought I'd let you guys know that I've started working on the next major release of react-markdown, which will switch from commonmark to markdown, thus enabling tables (among other things).

There will be some breaking changes to the API, but nothing that should take too long to fix.

**Comment by jeremejevs** [comment]
@rexxars 

Nice to hear, but which library in particular do you intend to use, and why abandon CommonMark? Why not [`markdown-it`](https://github.com/markdown-it/markdown-it), another CM-compatible library, [acknowledged by jgm](https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations#javascript), the main guy behind CM?

In my use case, if you were to use something non-CM, the difference would probably be minimal, since the only user-generated content we have is comments, which people rarely format, and the rest can be adjusted relatively easily. But what about those with gigabytes of Markdown data, which might render differently?

**Comment by rexxars** [comment]
@jeremejevs I'll continue to maintain [commonmark-react-renderer](https://github.com/rexxars/commonmark-react-renderer), which to be fair is pretty much where all the logic of react-markdown resides. In hindsight, I should have named this module `react-commonmark`, since that's what it currently renders. Perhaps now would be a good time to fork and publish just that.

**Comment by rexxars** [comment]
@jeremejevs  As in; being able to opt-out of non-commonmark types?

Are there any compatibility issues in particular you're worried about? For most people, I'd think that the move would result in little or no changes in the rendered output.

**Comment by jeremejevs** [comment]
@rexxars As in rendering everything the same way `commonmark.js` would. There are no issues in particular I'm worried about, I just know for sure that most renderers differ in one way or another. Take a look at [Babelmark's examples of divergences](https://babelmark.github.io/faq/#what-are-some-examples-of-interesting-divergences-between-implementations) (look for `markdown-it` as a representative of CommonMark).

**Comment by tbillington** [comment]
Just curious about the status of the implementation of tables, are any rough goals ?

**Comment by martellaj** [comment]
Anyone with a simple use-case and just needs table support, I found [react-remarkable](https://github.com/acdlite/react-remarkable) to be a light-weight solution that's easily swappable with `react-markdown`.

**Comment by rexxars** [comment]
Been caught up with real-life lately, but I'm going to work on react-markdown this weekend, hoping to get closer.

**Comment by tbillington** [comment]
@rexxars Which table format would you implement, github style?

**Comment by rexxars** [comment]
Yup, Github-style.

**Comment by agustinlg** [comment]
+1 for tables! thanks!

**Comment by sichvoge** [comment]
@rexxars do you have an update on this?

**Comment by rexxars** [comment]
Been in the hospital for the past week, and I am in no fit state to code right now. It's pretty close, but not willing to give estimates based on health

**Comment by dodekeract** [comment]
@rexxars Good luck with that! Don't worry about this issue and take your time. Nobody is forcing you. :smile:

**Comment by sichvoge** [comment]
Agree to @dodekeract. Health should always be first priority! Thanks for all your good work.

**Comment by simonbuerger** [comment]
@rexxars Sorry to hear. Thanks for all your hard work on this. 

And I'm with them ^ take care of yourself first!

**Comment by pnepe6** [comment]
Like everyone, I hope everything going well. You do a great job and your module rocks! Looking forward to see **tables** implementation. Take care of yourself.

**Comment by simen** [comment]
Awesome stuff! Really need github-style table support to display some release notes in an app I'm working on. Looking forward to it!

**Comment by rexxars** [comment]
The new release candidate for v3 has table support. Please read [this issue](https://github.com/rexxars/react-markdown/issues/96) for more information. Please give it a go and let me know if you encounter issues.

**Comment by rexxars** [comment]
Closing this issue to make it easier for me to keep track of pending issues.

**Comment by rwlaschin** [comment]
This is great, I really need tables as well.  

The other thing I noticed is that <br> doesn't render as expected.
