### ISSUE TITLE
Typings prevent use of `children` by forcing `source` attribute.

### ISSUE THREAD

**Issue by gRoberts84** [rexxars/react-markdown#196]
When using `<ReactMarkdown># Markdown Rocks</ReactMarkdown>` with a TypeScript based solution, TypeScript fails because Source is not marked as optional.

    (76,175): Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactMarkdown> & Readonly<{ children?: ReactNode; ...'.
     Type '{ children: Element; }' is not assignable to type 'Readonly<ReactMarkdownProps>'.
       Property 'source' is missing in type '{ children: Element; }'.

By changing the typings from 

    readonly source: string

to

    readonly source?: string

Everything worked nicely.

Do I need to put a PR in, or can someone quickly look into this on your end?

Thanks

**Comment by rexxars** [comment]
I'm not too familiar with TypeScript yet, but it looks to me like the definitions are missing `children` as well?

**Comment by gRoberts84** [comment]
I'm not 100% certain to be fair, but I do recall seeing that if you don't specify a definition for children, then it's implied as `any`, but you could specify `children: T` (T being the type you want to enforce)

I'm getting around it for the moment being by adding the ? to the source property.

**Comment by rexxars** [comment]
Published as 3.4.0
