### ISSUE TITLE
Using the backtick does not form the markdown when rendering

### ISSUE THREAD

**Issue by nommuna2** [rexxars/react-markdown#203]
Hello all, 

I may be using this wrong but I couldn't find a solution, so I will try here. 

In my code I have it structured like this....

     const source = `

     ## Team Resources Documentation
     A sentence

     A header
     * bullet points
     * bullet points
     * bullet points
     * bullet points `

Then I render it like so....
    `<ReactMarkdown source={source}/>`
But it does not render as markdown, just plain html. Any reasons why?

**Comment by jhynzar** [comment]
Why is this closed? it also happend to me?

**Comment by jhynzar** [comment]
Why is this closed? this also happened to me.

```
const sourceMarkdown = `
        \`\`\`
        code here
        \`\`\`
`;
```
