### ISSUE TITLE
Ordered list not being parsed if no blank line above the list

### ISSUE THREAD

**Issue by hrmoller** [rexxars/react-markdown#204]
The issue is verified at https://rexxars.github.io/react-markdown/

When using a custom list render with the first example below, the list will never be passed to the list render but just be parsed as plain text.

This will be parsed inaccurate
```markdown
Some text
1. Implements [GitHub Flavored Markdown](https://github.github.com/gfm/)
2. Renders actual, "native" React DOM elements
```

This will be parsed correctly
```markdown
Some text

1. Implements [GitHub Flavored Markdown](https://github.github.com/gfm/)
2. Renders actual, "native" React DOM elements
```

**Comment by rexxars** [comment]
This seems to be a bug inside of the parser ([remark-parse](https://github.com/remarkjs/remark)) - perhaps you could file an issue there?
