### ISSUE TITLE
Underline syntax is wrong

### ISSUE THREAD

**Issue by sergei-gilevich** [rexxars/react-markdown#209]
Hi. I added md text with underline syntax to the ReactMarkdown component, but I see '++sometext++' instead underline text.
```
<ReactMarkdown source={'++sometext++'} />
```
++123++

**Comment by rexxars** [comment]
[GitHub Flavored Markdown](https://github.github.com/gfm/) does not have any recognized syntax for underline.

**Comment by bubblegan** [comment]
asdasd
