### ISSUE TITLE
Bug in title display

### ISSUE THREAD

**Issue by dlutwuwei** [rexxars/react-markdown#21]
```
#title
# title
```
#title

# title

why the space between '#' and `title` must be added?

**Comment by rexxars** [comment]
Because react-markdown is currently following [commonmark](http://spec.commonmark.org/0.17/). It specifically says: 

> The opening sequence of # characters cannot be followed directly by a non-space character.

I'm fairly sure that I will be switching this to using a Markdown parser in the future, but right now there isn't any short-term fix for this - sorry.

**Comment by emirdeliz** [comment]
I have same issue
