### ISSUE TITLE
unwrapDisallowed removes numbers from ordered list

### ISSUE THREAD

**Issue by nbkhope** [rexxars/react-markdown#212]
Given a text like:

```
1.  Do something
```

I want it show to it as is, without it being converted to an unordered list. I tried using

```
<ReactMarkdown
  ...
  disallowedTypes={['list', 'listItem']}
  unwrappedDisallowed
/>
```

But it removes the `1.  ` from the text, giving me just

```
Do something
```

Is there any way of preventing that from happening?

**Comment by rexxars** [comment]
This will be solved when we can programatically disable parsing of nodes in remark-parse. There is a WIP PR for this https://github.com/rexxars/react-markdown/pull/223

**Comment by bjudson** [comment]
@nbkhope Try using the [`remark-disable-tokenizers`](https://www.npmjs.com/package/remark-disable-tokenizers) plugin to ignore the list tokens:

```
import remarkDisableTokenizers from "remark-disable-tokenizers";

<ReactMarkdown
  plugins={[
    [
      remarkDisableTokenizers,
      { block: ["list"] }
    ]
  ]}>
  {markdownContent}
</ReactMarkdown>
```

**Comment by aaronmw** [comment]
@rexxars What is the fix for this, exactly? The above-mentioned plugin is no longer supported in the latest version.

**Comment by wooorm** [comment]
Please don’t comment on 4 year old issues but ask a question according to the support guidelines.
Quick answer: probably, don’t use `disallowed*` stuff for this. Or use CSS.
