### ISSUE TITLE
Passing index information to renderers

### ISSUE THREAD

**Issue by beauroberts** [rexxars/react-markdown#213]
Hello! Thank you *so much* for creating and maintaining such an awesome library! 👏 

I'd like to be able to conditionally apply some styles based on a node's index under its parent, e.g. to remove some top margin from the first element and the bottom margin from the last element. Basically enabling some of the stuff that in CSS-land we would have done with `:first-child`, `:last-child`, `:nth-child`, etc.

If you're open to it, I have a PR that mirrors what you did with `rawSourcePos`, passing index information to non-tag renderers if a boolean prop on the `Markdown` component is set to `true`. Would love your feedback! And I'm particularly terrible at naming things so please feel free to suggest better alternatives!

Will open that PR momentarily.

**Comment by rexxars** [comment]
Thanks for your kind words! I will address some issues in your PR.

**Comment by rexxars** [comment]
Feature included in 3.6.0.

**Comment by ChristianMurphy** [comment]
@Dunridge this discussion is from over 6 years and also six major versions ago.
The API is very different now.

See the README for information on the current API.
If you have questions on how to do something open a discussion and include the context of what you want to solve.
https://github.com/orgs/remarkjs/discussions/new?category=q-a
