### ISSUE TITLE
Remark-parse invalid value error

### ISSUE THREAD

**Issue by fonsleenaars** [rexxars/react-markdown#216]
I tried using this library and even the simplest example gives me the following error. I've tried a few versions back and forward but it always seems to pop-up.

```jsx
import ReactMarkdown from 'react-markdown';
...
...
render() {
   const input = '# Test';
   return (
      <ReactMarkdown source={input} />
      <ReactMarkdown source="# Test" />
      <ReactMarkdown>
         # Test
      </ReactMarkdown>
   );
}
```
None of this component attempts seem to work. I'm using webpack 4 and React 16.

Console error:
```
set-options.js:37 Uncaught Error: Invalid value `/8df95e1fe7780fec0873a78ac40d96ec.json` for setting `options.blocks`
    at Of.setOptions (set-options.js:37)
    at Of.Parser (parser.js:16)
    at new Of (index.js:43)
    at Function.parse (index.js:277)
    at ReactMarkdown (react-markdown.js:32)
    at ProxyFacade (react-hot-loader.development.js:675)
    at mountIndeterminateComponent (react-dom.development.js:13381)
    at beginWork (react-dom.development.js:13821)
    at performUnitOfWork (react-dom.development.js:15864)
    at workLoop (react-dom.development.js:15903)
```

Thanks!

**Comment by fonsleenaars** [comment]
@adamblvck 
>You may need an appropriate loader to handle this file type. 

Are you loading the markdown content from a file by any chance? If you are, you'll need something like `raw-loader` for it to be imported/required properly as a string. Otherwise nevermind ;)

**Comment by rexxars** [comment]
@fonsleenaars I'm not able to reproduce this, could you create a minimal repository reproducing the issue?

**Comment by rexxars** [comment]
@adamblvck Your issue is a different one, it looks like your bundler (webpack, looks like?) is missing the json-loader (this is included by default in webpack >= 2.0.0, so I suspect you are using webpack 1.x?). See https://github.com/webpack-contrib/json-loader

**Comment by fonsleenaars** [comment]
@rexxars will do, I'll get one setup later this morning (who knows, perhaps through that I'll find the issue myself!).

**Comment by rexxars** [comment]
@fonsleenaars Did you figure this out?

**Comment by fonsleenaars** [comment]
Sorry not yet, got caught up in a big move, will update early next week after I've setup my desk!

**Comment by rexxars** [comment]
@mattyfew That seems odd, what is the content of `./node_modules/remark-parse/lib/block-elements.json`?

**Comment by fonsleenaars** [comment]
That didn't take long, the breaking code in the webpack config is this:

```
{
    type: 'javascript/auto',
    test: /\.json$/,
    use: [{
    loader: 'file-loader',
    }],
},
```

I've added this as a commented portion to the repository I linked above. If you checkout that repo and run it as is, it will work, if you then uncomment the code above in `webpack.config.js` you'll see the error.

**Comment by rexxars** [comment]
Thanks for the reproduced issue! 

I think that saying all JSON-files should be treated as text will break a lot of things... If this is something you use in your app, perhaps make sure that `node_modules` are not included in this rule (in the same way as the babel loader is configured)?

If you have specific dependency/dependencies inside of node_modules containing JSON files that you would like to be treated as text, perhaps use a `include` option for the loader for those specific paths?

I don't consider this to be a react-markdown issue at least - if you still feel like this is something that libraries should support, perhaps file an issue with [remark-parse]()https://github.com/remarkjs/remark?

**Comment by Iar0** [comment]
For who is using roolup and encounter something like this:

```
ERROR in ./node_modules/remark-parse/lib/block-elements.json
Module build failed (from ./node_modules/json-loader/index.js):
SyntaxError: Unexpected token ; in JSON at position 576
```

[Consider that the ORDER of the plugin matters](https://github.com/rollup/rollup-plugin-json/issues/6). Moving the json plugin before babel solved my problem

**Comment by reedasha** [comment]
Hello, I am having similar problem with the basic usage of the library
`<ReactMarkdown source={'# Test'} />`
I get the following error in my console
`Uncaught Error: Invalid value `[
  "address",
  "article",
  "aside",
  "base",
  "basefont",
  "blockquote",
...]
for setting options.blocks`

Did anyone encountered the same problem?

**Comment by jesobreira** [comment]
Same problem here, using Parcel (only the dist build throws this error).

**Comment by angelod1as** [comment]
Any solution to this?
