### ISSUE TITLE
secondary paragraphs do not get rendered 

### ISSUE THREAD

**Issue by ntregillus** [rexxars/react-markdown#217]
I am seeing that subsequent paragraphs are not rendering correctly

take this test scenario:

```
const testMd = `**this is rendered correctly**
so is this

this is **not** rendered correctly`;

const testJsx = () => <Markdown source={testMd} />

export default testJsx;

```

I am unsure why the last line is not rendered correctly....

**Comment by rexxars** [comment]
Seems correct to me. I'll need an output example if you want me to have a look at this.
