### ISSUE TITLE
Support loading react from CDN

### ISSUE THREAD

**Issue by dodekeract** [rexxars/react-markdown#22]
````
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react.min.js" charset="utf-8" crossorigin="anonymous"></script>
````
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: module "react" not found from "/home/dodekeract/code/manta-config-engine-app/node_modules/react-markdown/src/react-markdown.js"
    at notFound (/home/dodekeract/code/manta-config-engine-app/node_modules/browserify/index.js:803:15)
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browserify/index.js:754:23
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/index.js:185:24
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:44:14
    at process (/home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:113:43)
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:122:21
    at load (/home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /home/dodekeract/code/manta-config-engine-app/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)
````

React is not found, yes - because it's not installed via npm to save bandwidth. However, it will be available in the browser. Not sure how you can fix this, but it should be possible somehow.

**Comment by rexxars** [comment]
This is more of a packaging issue.

If you're using browserify:
`browserify --external react your-app.js > dest.js`

If you're using webpack, use the [externals](https://webpack.github.io/docs/library-and-externals.html) option

I've also made the library available as a UMD build, so you can drop it into a webpage. [See example](https://jsbin.com/vatubu/3/edit?html,js,output).
