### ISSUE TITLE
Links don't work if any characters in 'https' are uppercase

### ISSUE THREAD

**Issue by liamsain** [rexxars/react-markdown#221]
Hi. 
When trying to render this: `[link](Https://www.google.com)`, the href value comes through as 'javascript:void(0)'. same case for 'hTtps', 'htTps' etc, as well as all caps.

Any ideas for fixes /workarounds?

Thanks

**Comment by liamsain** [comment]
pr: https://github.com/rexxars/react-markdown/pull/222

**Comment by rexxars** [comment]
Thanks! Scheduled for 4.0
