### ISSUE TITLE
What do 'tight' and/or 'loose' mean for rendered items?

### ISSUE THREAD

**Issue by ekilah** [rexxars/react-markdown#224]
i.e.:
https://github.com/rexxars/react-markdown/blob/673ade7e134dea3a53cd796f7a970fc7a374381d/src/ast-to-react.js#L75

and:

https://github.com/rexxars/react-markdown/blob/673ade7e134dea3a53cd796f7a970fc7a374381d/index.d.ts#L107

**Comment by rexxars** [comment]
In "tight" lists, a paragraph will not be rendered.
In "loose" lists, a paragraph _will_ be rendered.

Tight list example:
```markdown
*   Bird
*   Magic
```

Output:
```html
<ul>
  <li>Bird</li>
  <li>Magic</li>
</ul>
```

Loose list example:
```markdown
*   Bird

*   Magic

```

Output:
```html
<ul>
  <li><p>Bird</p></li>
  <li><p>Magic</p></li>
</ul>
```

**Comment by ekilah** [comment]
I asked this question a few months ago, and just got confused about it again 😛 
might I suggest a quick readme note about it?

I'm not sure how up-to-date this repo is with `remark-parse`, but it looks like they might call this property `spread` instead of `loose` now... which is slightly confusing and makes it hard to find the documentation related to this feature: https://github.com/remarkjs/remark/commit/aab3c3e705aafef79d9237ea3f2355e8fae9fbaa
