### ISSUE TITLE
can not highlight code block

### ISSUE THREAD

**Issue by wqh17101** [rexxars/react-markdown#239]
code：
![image](https://user-images.githubusercontent.com/26429138/47638037-70df6280-db98-11e8-9d2d-f421d2ea755d.png)

result：
![image](https://user-images.githubusercontent.com/26429138/47638065-7fc61500-db98-11e8-94a6-66cfbca45ef2.png)

Expect：
![image](https://user-images.githubusercontent.com/26429138/47638089-92404e80-db98-11e8-88f2-a3ba6dc3959e.png)

**Comment by rexxars** [comment]
Syntax highlighting is not a part of react-markdown.
You can override the `code` renderer with something like [react-refractor](https://github.com/rexxars/react-refractor) or [react-lowlight](https://github.com/rexxars/react-lowlight) to achieve the result you desire.

**Comment by kc-beard** [comment]
@rexxars I ran into this issue too, I think what contributes to the confusion is that the demo site [shows syntax highlighting](https://rexxars.github.io/react-markdown/). It might be a good idea to add a line to the docs or to the demo site explaining that syntax highlighting doesn't come by default.

**Comment by jimmy-e** [comment]
[Here](https://medium.com/young-developer/react-markdown-code-and-syntax-highlighting-632d2f9b4ada)'s a good resource for those looking on how to add syntax highlighting.
