### ISSUE TITLE
renderers do not work with styled-components

### ISSUE THREAD

**Issue by macrozone** [rexxars/react-markdown#244]
very simple example:

```
import styled from 'styled-components'

const  Link = styled.a.attrs({
  target: '_blank',
})`
  color: blue;
`

const RENDERERS = {
  link: Link,
}

// later
 <ReactMarkdown renderers={RENDERERS}>this is a link: [click me](http://github.com)</ReactMarkdown>

```

throws: `Uncaught Error: Renderer for type `link` not defined or is not renderable`

which is weird, because they are just normal React-components. It should not make too much assumptions about the component. functions or React.Component or strings should be fine.

Workaround:

```
const RENDERERS = {
  link: props => <Link {...props} />,
}
```

**Comment by EmaSuriano** [comment]
+1 I'm having the same issue and used your workaround.

**Comment by oomathias** [comment]
I think `react-markdown` isn't compatible with `React.forwardref`.

**Comment by mlenser** [comment]
The link and heading renderers work fine for me via:
```
<Markdown
    renderers={{
      heading: HeadingRenderer,
      link: LinkRenderer,
    }}
/>
```
root, however will not render a fragment no matter what I do.

I tried adding the props hack above
```
const RootRenderer = ({
  children,
}) => (
  <React.Fragment>
    {children}
  </React.Fragment>
);

<Markdown
    renderers={{
      heading: HeadingRenderer,
      link: LinkRenderer,
      root: props => <RootRenderer {...props} />,
    }}
/>
```
but the root is always a `p`. I tried following the method to use it on #149, but can never get it to wrap the markdown in anything but a `p`. If I change the `RootRenderer` to instead use a `div` I then just get a div around my `p`.

Any ideas what is going on here?

**Comment by jessepinho** [comment]
FWIW, the line in question is here: https://github.com/rexxars/react-markdown/blob/master/src/ast-to-react.js#L12

**Comment by supadupdip** [comment]
I am also seeing this issue after upgrading styled-components from v4 to v5

**Comment by supadupdip** [comment]
Looking through the source @jessepinho is right, if you modify the line to include the object type it works

```
    if (
        typeof renderer !== 'function' &&
        typeof renderer !== 'string' &&
        typeof renderer !== 'object' &&
        !isReactFragment(renderer)
    ) {
        throw new Error(
            'Renderer for type `'.concat(node.type, '` not defined or is not renderable')
        );
    }
```

**Comment by mDibyo** [comment]
I am seeing the same issue with `React.memo` components.

`typeof React.memo(SomeComponent) === 'object'`. Think we would need to amend the check to check `renderer.$$typeof` as well. That attribute will be set for all kinds of components except function components.

**Comment by PerfectPixel** [comment]
Maybe the use of [react-is](https://www.npmjs.com/package/react-is) could be considered to cover all bases. With the downside of missing react 15 support. 🤷‍♂

**Comment by wooller** [comment]
Just ran into this issue as well

**Comment by dtothefp** [comment]
I'm having the same issue after having updated to `styled-components@4` from v3. Is there a fix coming?
