### ISSUE TITLE
More documentation related to renderers

### ISSUE THREAD

**Issue by annjawn** [rexxars/react-markdown#247]
Hi, great library. I am having a hard time understanding the usage of renderers. Is there a way to add some more documentation with small examples on how to use it? Basically my use case is pretty simple, i have have some markdown text in a `.md` file and I use Semantic UI React for UI components and I want to be able to use some of the Semantic UI components as renderers (like buttons etc.). Is that even possible?

**Comment by annjawn** [comment]
Nevermind.... got it working.. Thanks.

**Comment by el1f** [comment]
I think this is still an on point observation though. Some renderers provide extra props that aren't documented and that needs us to go look at the vanilla renderers implementation to see which props are needed by which renderer... a table in the readme.md would do a great job for that

**Comment by annjawn** [comment]
The way I did it was by `console.log` the props and looking at source code. Not ideal, but yes some more documentation on how to actually use the renderers would be very helpful specially since different renderers have different props that can be accessed. I also think there can be a few more default node types that can be supported like `<details>`.
