### ISSUE TITLE
Pass custom props to renderers

### ISSUE THREAD

**Issue by kislakiruben** [rexxars/react-markdown#257]
Hi,

I created a custom renderer for images to which I need to pass some custom event handlers when I load an image. What I am not being able to figure out is how to pass custom props (in my case event handlers) to renderers. Basically I want to do this:

```jsx
const Image = ({ onImageLoag, src }) => <img src={src} onImageLoag={onImageLoag} />;

const CustomMarkdownComponent = ({ onImageLoag }) => (
  <ReactMarkdown
    renderers={{
      image: Image
    }}
    source={someMarkdown}
  />
);

Image.propTypes = { ... };
CustomMarkdownComponent.propTypes = { ... };
```

But, obviously this doesn't work, as the `image` node only get passed `alt`, `title` and `source`.

One option would be to pass the renderer straight in, but in this case I can't add prop types validation for `image` and ESLint complains about missing prop type validation:
```jsx
const CustomMarkdownComponent = ({ onImageLoag }) => (
  <ReactMarkdown
    renderers={{
      image: ({ onImageLoag, src }) => <img src={src} onImageLoag={onImageLoag} />;
    }}
    source={someMarkdown}
  />
);
```

Is there another way which I'm not aware of or should I stick with the approach from above (and just ignore ESLint)?

**Comment by kislakiruben** [comment]
I ended up doing this:
```jsx

const CustomMarkdownComponent = ({ onImageLoag }) => {
  const Image = ({ src }) => <img src={src} onImageLoag={onImageLoag} />;

  Image.propTypes = { ... };

  return (
    <ReactMarkdown
      renderers={{
        image: Image
      }}
      source={someMarkdown}
    />
  );
};

CustomMarkdownComponent.propTypes = { ... };
```

**Comment by el1f** [comment]
That's probably the intended use, I think renderers should only bear the minimum required props to render their block, having every extra prop passed by their containers
