### ISSUE TITLE
multi-line rows in tables

### ISSUE THREAD

**Issue by AlysG** [rexxars/react-markdown#258]
Is it possible to have a multi-line row in a table ?
I test pandoc "grid_tables" syntax and "<br>" without success. A syntax is already supported in react-markdown?

**Comment by rexxars** [comment]
Not as far as I know. It's not part of the markdown spec. You could always ask in the [remark](https://github.com/remarkjs/remark) ecosystem - they allow you to get more nitty-gritty.
