### ISSUE TITLE
Auto-linking URLs in text

### ISSUE THREAD

**Issue by BHSPitMonkey** [rexxars/react-markdown#26]
I'm aware CommonMark doesn't specify this behavior, but would an option to enable auto-linking URLs found in text (like GitHub does) be considered?

**Comment by rexxars** [comment]
Not currently. I've been pondering on switching to a different parser in the future, but until this happens  I'm not going to implement it, sorry.

**Comment by elimisteve** [comment]
Anyone come up with a good solution to this?  Thanks.

**Comment by gajus** [comment]
> Not currently. I've been pondering on switching to a different parser in the future, but until this happens I'm not going to implement it, sorry.

This should remain an open issue.

**Comment by Kadrian** [comment]
Is this actually possible today? I looked through the [remark list of plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins) but also couldn't find anything related there 🤔

**Comment by ChristianMurphy** [comment]
It's a part of GitHub flavored markdown, and can be enabled with remark-gfm (example in the readme https://github.com/remarkjs/react-markdown#use, and demo at https://remarkjs.github.io/react-markdown/)
