### ISSUE TITLE
[HELP] Render Markdown inside HTML tags

### ISSUE THREAD

**Issue by victorgcramos** [rexxars/react-markdown#269]
Hi guys! I'm new at using React Markdown, and I want to know if it is possible to render the markdown "tags" (like "#", "##" for headings), inside HTML tags when _scapeHtml_ is disabled. You can see by the following picture, that **bold** and _italic_ terms are so far so good. Thank you!
![html-markdown-example](https://user-images.githubusercontent.com/22639213/51874670-0ed5fb00-2349-11e9-96e4-8703985dec92.png)

**Comment by upperwal** [comment]
```html
<div className="one">

* one
* two

</div>
```

Leave a blank line after and before your HTML tags.
Original Issue: https://github.com/jupyter/notebook/issues/4504
