### ISSUE TITLE
Support "markdown" attribute for html tags

### ISSUE THREAD

**Issue by receter** [rexxars/react-markdown#279]
In some parsers (eg. the parser used in strapi) having a html element with markdown="1" will cause the content to be parsed as markdown. This is currently not the case for react-markdown.

`<p class="intro" markdown="1">**I want to be bold**</p>`

Currently it causes wrong expactations when using a strapi backend together with this package in the frontend.

**Comment by rexxars** [comment]
Not going to do this, I'm afraid.
