### ISSUE TITLE
Inline HTML tags with classnames are broken

### ISSUE THREAD

**Issue by 1999** [rexxars/react-markdown#285]
First of all, thanks for this great project! The issue I have is related to #194 but I didn't get the clear idea of how to make it work. This is the Markdown that we have:

```
# heading

<span class="lozenge">Yes</span>

some text
```

HTML is rendered like this:
```
<span><span class="lozenge"></span></span>
Yes
<span></span>
```

The issue is that the "lozenge" class is important for us - it has some styling and with this rendering "Yes" string is not styled at all.

**Comment by rexxars** [comment]
Could you try v4.0.8?
If it doesn't work, you might need to use the `with-html` version:
```js
const ReactMarkdown = require('react-markdown/with-html')
```

**Comment by 1999** [comment]
Thanks :) we're on the same team with @nicolasv so I'm gonna close this issue. Seems like the HTML plugin should solve the issue.

**Comment by SachaG** [comment]
Using `with-html` also worked for me, thanks!
