### ISSUE TITLE
Accessiblity support

### ISSUE THREAD

**Issue by sahilkhan99** [rexxars/react-markdown#288]
Hello Team,
Just want to check does the React Markdown component has inbuilt Aria support for accessibility?

Cheers,
Irfan

**Comment by rexxars** [comment]
I'm not super familiar with aria/accessibility, I regret to say. If there are aria tags we could add based on the markdown spec, I'd be happy to implement them.

**Comment by rexxars** [comment]
Closing this. Feel free to comment if there is specific things we could do to improve the accessibility of react-markdown.
