### ISSUE TITLE
Render react-router Link

### ISSUE THREAD

**Issue by suancarloj** [rexxars/react-markdown#29]
Hello,

is there a way to replace the links by react-router link ?

Thanks :)

**Comment by rexxars** [comment]
Hi and sorry for not getting back to you sooner.

Yes, using custom renderers this is fairly easy:

```js
const React = require('react')
const ReactDOM = require('react-dom')
const Markdown = require('react-markdown')
const Link = require('react-router').Link

function RouterLink(props) {
  return (
    props.href.match(/^(https?:)?\/\//)
      ? <a href={props.href}>{props.children}</a>
      : <Link to={props.href}>{props.children}</Link>
  );
}

ReactDOM.render(
  <Markdown
    source="Some text with a [link](/path) to try out"
    renderers={{Link: RouterLink}}
  />,
  document.body
)
```

You can find this example and more in a new repository I created: [react-markdown-examples](https://github.com/rexxars/react-markdown-examples)

**Comment by HeChenTao** [comment]
If I want to render a custome component, does it support?

**Comment by rexxars** [comment]
Yes, custom components are supported just fine. Like the above example, just find the node you want a custom renderer for and specify it in `renderers`. See [this page](https://github.com/rexxars/commonmark-react-renderer#type-renderer-options) for the props the renderer will receive,

**Comment by joepsz** [comment]
@rexxars thanks for sharing! It works pretty good, but fails for `mailto:` links. 

I ended up matching anything that starts with a `\` and flipping the ternary operator:

```` javascript
function RouterLink(props) {
  return (
    props.href.match(/^\//)
      ? <Link to={props.href}>{props.children}</Link>
      : <a href={props.href}>{props.children}</a>
  );
}

````

**Comment by worldsayshi** [comment]
I ended up using this method for determining whether to use react link or not: https://stackoverflow.com/a/28054735/439034

**Comment by pnepe6** [comment]
How about if I need to have title for all my links ?

**Comment by SachaG** [comment]
I spent 15 minutes trying everything I could to make this work before realizing that it shouldn't be

```
renderers={{Link: RouterLink}}
```

But instead: 

```
renderers={{link: RouterLink}}
```

(note the small "l" in `link`!)

**Comment by tomekrozalski** [comment]
@SachaG I just spent an hour :dancing_men: Thanks!

**Comment by CoderSpinoza** [comment]
@SachaG Haha, spent only 20 minutes before seeing your comment. Thank god I am lucky. :)

**Comment by khanzzirfan** [comment]
Here we go guys, here how I created a react router link based on anchor link. With the use of astPlugins and preprocessing html nodes. 

https://codesandbox.io/s/react-markdown-4blv2
