### ISSUE TITLE
Using a custom renderer for a paragraph is not allowing styling overrides

### ISSUE THREAD

**Issue by brspurri** [rexxars/react-markdown#290]
I am trying to override the `margin` css property of the `<p></p>` tag rendered by **react-markdown**. (The paragraph tag has margins by default, and I need to set them to 0). I can see that setting the margins to 0 (via Chrome Developer Tools) works, so I know I need to have **react-markdown** add a style onto the rendered `<p></p>`.

Currently, I have the code:
```
<ReactMarkdown
    source={this.props.message}
    renderers={{ p: ChatViewRowTypeTextMarkdown }}
 />
``` 

My `ChatViewRowTypeTextMarkdown` class is:
```
import * as React from "react";
import PropTypes from "prop-types";
import { withStyles, createStyles, Theme, WithStyles } from "@material-ui/core/styles";

const styles = (theme: Theme) => createStyles({});

interface IState {}

interface IProps extends WithStyles<typeof styles> {
  classes: any;
  value: string;
}

class ChatViewRowTypeTextMarkdown extends React.PureComponent<IProps, IState> {
  element: any;
  constructor(props: IProps) {
    super(props);
    this.setRef = this.setRef.bind(this);
  }

  setRef(e: any) {
    this.element = e;
  }

  render() {
    const { classes } = this.props;

    return (
      <p ref={this.setRef} style={{ margin: 0 }}>
        {this.props.value}
      </p>
    );
  }
}

(ChatViewRowTypeTextMarkdown as React.ComponentClass<IProps>).propTypes = {
  classes: PropTypes.object.isRequired
} as any;

export default withStyles(styles)(ChatViewRowTypeTextMarkdown);
```

You can see that the `<p></p>` contains an inline style to set the margin to 0.

However, this is not working as expected. Does anyone have any idea how to get **react-markdown** to render a paragraph element with styling overrides?

**Comment by rexxars** [comment]
You are passing `p` as a renderer name, but it should be `paragraph`. See the list of node types here: https://github.com/rexxars/react-markdown#node-types
