### ISSUE TITLE
Question: approach to custom markdown?

### ISSUE THREAD

**Issue by zeg-io** [rexxars/react-markdown#291]
I'm wanting to implement custom interpretation for a couple things, an example would be tags.  I can of course pre-process the text and pull what I need for organization, but I'd like to style them while displaying.

I've briefly looked through the plugin examples but they seem based on looking for html and passing it through. I can of course come up with regex to identify my markdown, I'm just less sure what to do with it then in terms of injecting the generated html text.

Is there a simple example of this somewhere?

So for example (syntax for it isn't thought through yet):

`!# tag1, tag2, location, city`

I'd want to render that as something like:

```html
<ul class="tags">
  <li>tag1</li>
  <li>tag2</li>
  <li>location</li>
  <li>city</li>
</ul>
```

**Comment by rexxars** [comment]
I think you should look into the [remark](https://github.com/remarkjs/remark) ecosystem, which lets you get more low-level in terms of parsing. This is out of scope for react-markdown. Good luck!
