### ISSUE TITLE
Markdown within HTML?

### ISSUE THREAD

**Issue by zeg-io** [rexxars/react-markdown#295]
I'm using markdown for static pages on my site, this is great.  I have a single page though which requires slightly more than markdown can deliver, a list of service tiers (that standard card format that is prevalent.

I turned on HTML so I can dump divs and the like within the markdown, so that's good.

I'm looking for a way to be able to still interpret the internals of html tags with markdown through a setting or a plugin.  That way I can do something like this, which is all I need to be able to use CSS to format it.

```md
<div>

  ### Service Offering

  * Feature 1
  * Feature 2
  * Feature 3

</div>
```

**Comment by 1999** [comment]
According to Markdown spec (okay, recommendations), only inline HTML elements can have Markdown. Block HTML elements should not parse and render Markdown content.

**Comment by rexxars** [comment]
@1999 is correct here. If you need more flexibility in terms of parsing, take a look at the [remark](https://github.com/remarkjs/remark) ecosystem
