### ISSUE TITLE
Code not rendering

### ISSUE THREAD

**Issue by myyellowshoe** [rexxars/react-markdown#300]
I'm a bit unsure why something like this doesn't work: (Markdown taken from the docs)

    <ReactMarkdown source={`

      \`\`\`js
      var React = require('react');
      var Markdown = require('react-markdown');

      React.render(
        <Markdown source="# Your markdown here" />,
        document.getElementById('content')
      );
      \`\`\`
    `}
    />

Instead of rendering a codeblock it just renders the plain old text with backticks. :O
Would suggest updating the documentation to provide some more code examples inside of react.

Whats up with this?

Thanks!

**Comment by rexxars** [comment]
Not able to reproduce:
```js
test('foo', () => {
  const component = renderer.create(
    <Markdown
      source={`

  \`\`\`js
  var React = require('react');
  var Markdown = require('react-markdown');

  React.render(
    <Markdown source="# Your markdown here" />,
    document.getElementById('content')
  );
  \`\`\`
`}
    />
  )

  expect(component.toJSON()).toMatchInlineSnapshot(`
    <pre>
      <code
        className="language-js"
      >
        var React = require('react');
    var Markdown = require('react-markdown');
    
    React.render(
      &lt;Markdown source="# Your markdown here" /&gt;,
      document.getElementById('content')
    );
      </code>
    </pre>
  `)
})
```

**Comment by stellarbear** [comment]
Same issue
Using Material UI, ts and cra
