### ISSUE TITLE
Is there a way to wrap elements until next heading ?

### ISSUE THREAD

**Issue by manuquentin** [rexxars/react-markdown#309]
Hi !
I would like to make all my content between 2 heading in a wrapper, like :
```
# block 1
text 1

# block 2
text 2
```

To be renderer as :
```
<div class="wrapper>
  <h1>block 1</h1>
  <p>text 1</>
</div>
<div class="wrapper>
  <h1>block 2</h1>
  <p>text 2</p>
</div>
```

I've tried with `heading` rendering but I don't find a way to render the content to the next `heading` block.

Is there a way to do it with `react-markdown` ?

**Comment by n44ps** [comment]
Hi @manuquentin,

I've been doing this using [remark-sectionize](https://github.com/jake-low/remark-sectionize) but it would not work properly so I ended up modifying it a bit :

```javascript
import visit from 'unist-util-visit-parents';
import findAfter from 'unist-util-find-after';

/* inspired by remark-sectionize */

export function sectionize() {
  function transformer(tree: any) {
    const MAX_HEADING_DEPTH = 6;

    // tslint:disable-next-line: no-increment-decrement
    for (let depth = MAX_HEADING_DEPTH; depth > 1; depth--) {
      visit(
        tree,
        (node: any) => node.type === 'heading' && node.depth === depth,
        sectionize
      );
    }

    function sectionize(node: any, ancestors: any) {
      const start = node;
      const parent = ancestors[ancestors.length - 1];

      const isEnd = (node: any) =>
        node.type === 'heading' && node.depth <= start.depth;
      const end = findAfter(parent, start, isEnd);

      const startIndex = parent.children.indexOf(start);
      const endIndex = parent.children.indexOf(end);

      const between = parent.children.slice(
        startIndex,
        endIndex > 0 ? endIndex : undefined
      );

      const section = {
        type: 'section',
        children: between,
        position: parent.position,
        data: {
          hName: 'section'
        }
      };

      parent.children.splice(startIndex, section.children.length, section);
    }
    return tree;
  }

  return transformer;
}
```

And then adding the props to ReactMarkdown : `astPlugins={[sectionize()]}`
Hope it will help you :)

**Comment by manuquentin** [comment]
Thanks @n44ps !

**Comment by MarcusOy** [comment]
Hey @n44ps , I am trying to use your adaptation, however, it seems to not be doing anything to my node tree. I do not know how the unist-utils work, however, debugging your code resulted in the `sectionize(node, ancestors)` function to not be triggered at all. Tested with all sorts of configurations with renderers, plugins, etc on pretty normal looking markdown content.

**Comment by demipixel** [comment]
For those lurking, the code above works, you just need to change `astPlugins={[sectionize()]}` to `remarkPlugins={[sectionize]}` and `renderers` to `components`.
