### ISSUE TITLE
<img/> element can't trigger the transformImageUri function

### ISSUE THREAD

**Issue by RubyZhuuu** [rexxars/react-markdown#31]
Hello.
I have some `<img/>` tags in markdown, and I want to handle the src attrs in these elements. So I use the transformImageUri function, hoping to get original uri as input and return new uri.
However, I found that if the element is already  `<img/>` in the markdown, it can't trigger the transformImageUri function. Any solution to deal with this condition? Thx

**Comment by rexxars** [comment]
Not currently, no. We'd have to implement an HTML parser to be able to properly address use cases as this. Just a can of worms I am not prepared to open at this point - sorry.
