### ISSUE TITLE
Cant't disable transformLinkUri because typescript throws an error

### ISSUE THREAD

**Issue by visuallization** [rexxars/react-markdown#317]
Hi guys!

Thanks for react-markdown and the effort you put in.
I really appreciate it! :)

I currently have a problem when using react-markdown with typescript.
Specifically when I want to disable transformLinkUri by assigning null, my ts compiler throws an error that null is not a valid parameter.

![image](https://user-images.githubusercontent.com/6199277/59157037-84df3100-8aa4-11e9-9562-1d9118774a5e.png)

I create a PR, please review it and let me know what you guys think.
https://github.com/rexxars/react-markdown/pull/316

Cheers,
Florentin

**Comment by rexxars** [comment]
Fixed in v4.0.9
