### ISSUE TITLE
Request for Options syntax clarification

### ISSUE THREAD

**Issue by dbvrac** [rexxars/react-markdown#318]
I'm using this with Redux. I map through a an array in my Store to grab names for several items being displayed. I display their names like this: `<p>{node.name}</p`. Each node also has a readme.md URL, and I would like to display the rendered contents of that file. I can get a link to that information like this: `<ReactMarkdown source={node.readmeUrl} />`, but I don't quite understand how to use all of the Options.

**Comment by rexxars** [comment]
This is out of scope for this project. Maybe [remark](https://github.com/remarkjs/remark) is what you are looking for?
