### ISSUE TITLE
Internal links are not working.

### ISSUE THREAD

**Issue by vasanthkumar97** [rexxars/react-markdown#319]
I am using 4.0.9 version. I have markdown content like

`## Quick Links

- [Books](#books)

## Books

- abc
`

React Js code 
`
 <ReactMarkdown
            source={markDownContent}

        />
`

The entire markdown content is being displayed, links to external webpages are working, but internal links are not working, they are directing me to /corresponding-link, which doesn't exist in my route.

thanks,
Vasanth

**Comment by rexxars** [comment]
I don't know what this means. Please provide a gist or reduced test case, and I'll reopen if I can reproduce.
