### ISSUE TITLE
Heading immediatly after `<br />` not rendered

### ISSUE THREAD

**Issue by moimael** [rexxars/react-markdown#33]
Hi,

I just tried your component on some markdown we had in database and have an issue wit headings not rendering when placed immediately after an HTML `<br />` tag.

example : 
```Markdown
<br />
#### Test
```

Any idea why ?

Thanks !

**Comment by rexxars** [comment]
This is how the Commonmark specification defines it. HTML blocks should be followed by two or more newlines. You can see the AST generated here: http://spec.commonmark.org/dingus/

Sorry for the late reply.
