### ISSUE TITLE
Does this library support math formula?

### ISSUE THREAD

**Issue by rickygeng** [rexxars/react-markdown#331]
I am just curious if this library supports math formula like Latex?

**Comment by jacob-alford** [comment]
I made a quick component to replace one of the renderers, like strikethrough.  It involves [Katex](https://katex.org/) and `dangerouslySetInnerHTML`. I'm not done with it yet, but I wanted to emulate [react-latex](https://github.com/talyssonoc/react-katex).  It doesn't seem like it's rendering quite right, but if you're interested I can post the code somewhere once I finish it :-)

**Comment by jacob-alford** [comment]
Ended up replacing a pattern in the text that feeds into Markdown, and then intercepting it within strikethrough.  A few problems with the markdown renderer escaping backslashes, but it's safe and functional *hooray*

**Comment by rickygeng** [comment]
Thanks. But for now I am gonna stick to react-latex.
