### ISSUE TITLE
Checkboxes Render In An Unordered List

### ISSUE THREAD

**Issue by AmySchaplowsky** [rexxars/react-markdown#332]
Checkboxes are rendering in an unordered list which causes the checkbox to render a bullet in front of the checkbox.

![image](https://user-images.githubusercontent.com/40578818/63718612-923cc980-c810-11e9-8e71-e175a712a7e2.png)

Is this standard or can we get checkboxes styled outside of a list to avoid this issue?  I can't just hide them in css because then the legitimate unordered lists also lose their styling

**Comment by Tokenyet** [comment]
I also see this behavior in the demo page, Would you,mind to explain what you found or why you close this issue?

**Comment by AmySchaplowsky** [comment]
My issue was resolved by being able to override the checkbox component to
not display the bullets.  The default functionality still displays as
mentioned in the bug.
