### ISSUE TITLE
Why is a ‘#’ and two ‘##’ showing the effect is the same

### ISSUE THREAD

**Issue by hyndaniel** [rexxars/react-markdown#34]
such as this 
![image](https://cloud.githubusercontent.com/assets/18070336/17474322/eb071e54-5d87-11e6-984b-e80e3162f843.png)
and there is my code 
![image](https://cloud.githubusercontent.com/assets/18070336/17474344/037f82a0-5d88-11e6-8efc-f908efb3e94a.png)

Please help me

**Comment by rexxars** [comment]
Probably because your CSS has the same font-size for both `h1` and `h2`. 

Works fine here: http://rexxars.github.io/react-markdown/

**Comment by hyndaniel** [comment]
But I did't have any CSS or less file, only a index.jsx. 
Thanks for reply.
