### ISSUE TITLE
Missing TypeScript definitions for html-parser

### ISSUE THREAD

**Issue by alexkirsz** [rexxars/react-markdown#340]
Neither `'react-markdown/plugins/html-parser'` nor `'react-markdown/with-html'` expose TypeScript definitions.

**Comment by ludgerey** [comment]
Any progress here? The PR seems to be a legit solution to the problem. Why isn't it merged yet?

However as this is not merged yet, how would you integrate the fix today?

**Comment by ludgerey** [comment]
Adding a `globals.d.ts` containing only this 👇 fixed the problem for me. 

```
declare module 'react-markdown/with-html';
```

However would be nice to have this in the package itself.
