### ISSUE TITLE
Code and blockquotes not displaying as expected

### ISSUE THREAD

**Issue by AlexLerman** [rexxars/react-markdown#35]
I could just be doing something wrong, but this is how the [live demo](http://rexxars.github.io/react-markdown/)  text gets displayed in my app:

<img width="649" alt="screen shot 2016-08-08 at 10 01 52 am" src="https://cloud.githubusercontent.com/assets/1694206/17489429/e07c3648-5d52-11e6-9d51-6216053121b2.png">

The code while code like is missing the box and the coloring
The blockquote is missing the left-hand bar.

looking at the elements, the code element is very different in my page than it is on the demo page:

Mine:
<img width="526" alt="screen shot 2016-08-08 at 10 38 45 am" src="https://cloud.githubusercontent.com/assets/1694206/17489790/9569733a-5d54-11e6-865e-33aeafe358c3.png">

Demo:
<img width="542" alt="screen shot 2016-08-08 at 10 38 31 am" src="https://cloud.githubusercontent.com/assets/1694206/17489791/957ba834-5d54-11e6-9286-2b770fc06daa.png">

My package.json reads:
    "react": "^15.2.1",
    "react-dom": "^15.1.0",
    "react-markdown": "^2.4.2",

Any help would be greatly appreciated! Thanks!

**Comment by rexxars** [comment]
The default configuration doesn't do any syntax highlighting or styling. This means it's up to the implementer to choose how things should look.

Blockquotes can be easily styled. The demo uses the following CSS, for instance:
```css
blockquote {
    color: #666;
    margin: 0;
    padding-left: 3em;
    border-left: 0.5em #eee solid;
}
```

The demo uses [highlight.js](https://highlightjs.org/) for syntax highlighting through a custom renderer.
See [demo/src/code-block.js](https://github.com/rexxars/react-markdown/blob/master/demo/src/code-block.js) for how that works, and [demo/src/demo.js](https://github.com/rexxars/react-markdown/blob/master/demo/src/demo.js#L67-L69) for how to enable the renderer.

Of course, this approach relies on hljs being loaded into the DOM already.

I also have a repository called [react-markdown-examples](https://github.com/rexxars/react-markdown-examples) which includes a better (though more complicated) example of syntax highlighting, using [react-lowlight](https://github.com/rexxars/react-lowlight).

**Comment by brownbl1** [comment]
Thanks for the comments here. Was looking for the same thing. It might make sense to include a note about the examples repo in the main README.

**Comment by DCapella** [comment]
If it helps anyone who comes here later, if you're using bootstrap, it'll automatically help style it.

**Comment by NapolDeveloper** [comment]
Thanks comments!
