### ISSUE TITLE
Mathjax is supported?

### ISSUE THREAD

**Issue by MontoyaAndres** [rexxars/react-markdown#357]
I want to make a text editor (something similar to Google Docs, but just with the real-time and share with my friends the doc) but dedicated to math. Does this project support all the characters used for it? Also, tables, charts, etc?

If not, what can I use?

Thanks!

**Comment by callmeYe** [comment]
https://medium.com/@MatDrinksTea/rendering-markdown-and-latex-in-react-dec355e74119

**Comment by MontoyaAndres** [comment]
Hey! Thank you! That package supports what Google Docs has? I mean, if you see the rich editar that this page has, it's too big... React-markdown can have all of this?

**Comment by callmeYe** [comment]
Maybe you can try SimpleMDE+marked+highlight .

**Comment by grabantot** [comment]
> https://medium.com/@MatDrinksTea/rendering-markdown-and-latex-in-react-dec355e74119

This is just beautiful.

**Comment by MontoyaAndres** [comment]
Thanks to everyone that helped me with this!

**Comment by antoineFrau** [comment]
Hi, I tried to implement this into a custom react app (https://github.com/antoineFrau/react-markdown-math), but the rerenders math and mathinline is not triggered. I can't really understand what I'm doing wrong.
```
const source= `Lift($L$) can be determined by Lift Coefficient ($C_L$) like the following
equation.

$$
L = \frac{1}{2} \rho v^2 S C_L
$$`;
...
renderers: {
            ...props.renderers,
            math: ({ value }) => {
                console.log("math equation") // Never logs
                return <MathJax.Node formula={props.value} />
            },
            inlineMath: ({ value }) =>{
                console.log("azeaz") // Never logs
                return <MathJax.Node inline formula={props.value} />
            }
        }
```

Does someone make this works with last version ?

**Comment by vladtimss** [comment]
> > https://medium.com/@MatDrinksTea/rendering-markdown-and-latex-in-react-dec355e74119
> 
> This is just beautiful.

how use it with typescript?

**Comment by ChristianMurphy** [comment]
Please see the readme it gives an example with Katex.
https://github.com/remarkjs/react-markdown#use-remark-and-rehype-plugins-math
Which also can be swapped for math jax https://github.com/remarkjs/remark-math/tree/main/packages/rehype-mathjax#rehype-mathjax
