### ISSUE TITLE
Unable to target image/imageReference nodes via renderers prop

### ISSUE THREAD

**Issue by matborowiak** [rexxars/react-markdown#362]
I'm fighting with this for few hours now, and cant solve it... 

What I'm trying to do is to target markdown `image` with `renderers` prop in any possible way. I tried even injecting html into markdown - no success. I thought maybe the reason is that images in output html are wrapped in `<p>` tags,  but funny thing is that Im not able to target `paragraph` either, or even `break`. I managed to make my `ImageComponent` run only with `heading` and `text`.

I checked other issues, but without luck. Can somebody help me here? 
All I want to do is to target images, so I can run my custom component over them.

Here is a markdown I'm working with:
```
#### <center> Some Heading </center>

![nov-5-2019](/img/5-nov-4hr.png "4hr chart")

<img src="/img/5-nov4hr.png"></img>

[![nov-5-2019](/img/5-nov-4hr.png "4hr chart")](https://www.google.com/)

<br>

Amet quis pariatur fugiat reprehenderit laboris et reprehenderit 
consequat ullamco nostrud minim sunt nisi. Ad ad elit sit mollit pariatur 
nostrud ullamco adipisicing anim.

<br>
```

Test component I'm trying to make run:
```
const ImageComponent = () => {
  debugger
  return (
  <div>
    {console.log('TEST')}
    TEST TEST
  </div>
)}
```

ReactMarkdown component:
```
  return (
    <div className={componentName + ' ' + order}>
      <ReactMarkdown 
          source={source} 
          escapeHtml={false} 
          renderers={{ image: ImageComponent }} 
      />
    </div>
  )
```

**Comment by prokizzle** [comment]
I like to pass in a ref with the image component that I can access later.

```
const ImageComponent = ref => () => {
  debugger
  return (
  <div ref={ref}>
    {console.log('TEST')}
    TEST TEST
  </div>
)}
```

```
  const imageRef = useRef();

  return (
    <div className={componentName + ' ' + order}>
      <ReactMarkdown 
          source={source} 
          escapeHtml={false} 
          renderers={{ image: ImageComponent(imageRef }} 
      />
    </div>
  )
```

**Comment by matborowiak** [comment]
> I like to pass in a ref with the image component that I can access later.

The problem is function ImageComponent never gets to run (as debugger never turns on, as indication of this function running). Your code didn't solve that issue, or maybe I got something wrong.
