### ISSUE TITLE
unwrapDisallowed should apply to types not included in allowedTypes too

### ISSUE THREAD

**Issue by ajbeaven** [rexxars/react-markdown#38]
It seems that `unwrapDisallowed` only applies to those types included in `disallowedTypes`. If instead you're whitelisting the types using the `allowedTypes`, it doesn't seem to unwrap those types that are _not_ included.

**Comment by rexxars** [comment]
Sorry for not responding to this earlier. Life, and such.

Can't seem to reproduce this?

```jsx
<ReactMarkdown
  source="Espen *initiated* this, but has had several **contributors**",
  allowedTypes={['Text', 'Paragraph']},
  unwrapDisallowed
/>
```

Renders: 
```html
<p>Espen initiated this, but has had several contributors</p>
```

`Emphasis` and `Strong` are not part of the allowed types, but the text node children are unwrapped.

If you have a reproducible test case, please comment and I'll reopen.

**Comment by ajbeaven** [comment]
Just getting around to playing around with this project again, hence the slow response. It still seems to occur in v2.4.2. Apologies, I should have added my test case to the OP.

```
<ReactMarkdown 
  source="_You_ want to tell me, and I have no objection to hearing it."
  containerTagName="span"
  unwrapDisallowed={true}
  allowTypes={['Emph']}
  escapeHtml={true} 
/>
```

Renders (incorrectly): 
```
<span>
  <p>
    <em>You</em> want to tell me, and I have no objection to hearing it.”
  </p>
</span>
```

I wouldn't expect that the `<p>` tags would be there as I have not explicitly allowed Paragraph in `allowTypes`.

Instead, I have to accomplish this like so:

```
<ReactMarkdown 
  source="_You_ want to tell me, and I have no objection to hearing it."
  containerTagName="span"
  unwrapDisallowed={true}
  disallowedTypes={['Paragraph']}
  escapeHtml={true} 
/>
```

Renders (correctly): 
```
<span>
    <em>You</em> want to tell me, and I have no objection to hearing it.”
</span>
```

Using `allowTypes` is a far safer approach so I'd much prefer to use that if I can.

**Comment by arvinio** [comment]
> Sorry for not responding to this earlier. Life, and such.
> 
> Can't seem to reproduce this?
> 
> ```js-jsx
> <ReactMarkdown
>   source="Espen *initiated* this, but has had several **contributors**",
>   allowedTypes={['Text', 'Paragraph']},
>   unwrapDisallowed
> />
> ```
> 
> Renders:
> 
> ```
> <p>Espen initiated this, but has had several contributors</p>
> ```
> 
> `Emphasis` and `Strong` are not part of the allowed types, but the text node children are unwrapped.
> 
> If you have a reproducible test case, please comment and I'll reopen.

Just pitching in to let you know that I'm experiencing a similar problem.
Version 4.0.6.

**Problem**: If my source starts with 4 whitespaces, it will be treated as `code` and disappear.

**Eg.**
 ```js-jsx
 <ReactMarkdown
   source="    Test sentence.",
   allowedTypes={['Text', 'Paragraph']},
   unwrapDisallowed
 />
```

**Expected output: **
 ```
 <p>Test sentence</p>
 ```

**Actual Output: **
 ```
 <p></p>
 ```

**My dirty fix:**

Add `Code` to `allowedTypes`, then in `renderers` add:
```js-jsx
code: () => {
      return source;
    }
```
