### ISSUE TITLE
Display raw markdown instead of unwrapping

### ISSUE THREAD

**Issue by skh-** [rexxars/react-markdown#387]
Hello, thanks for this great library. 

Is there a way I can show the raw markdown for `disallowedTypes`?

**Example 1**
- `disallowedTypes={['strong']}` 
- `unwrapDisallowed={true}`
- Markdown: `**test**` 

Display `**test**` instead of `test`.

Further, if `unwrapDisallowed={false}`, this content will be completely empty.

**Example 2**
- `disallowedTypes=['strong']` 
- `unwrapDisallowed={true}` (or false)
- Markdown: `[](http://example.com)` 

Regardless of the `unwrapDisallowed` setting, in this scenario the result printed will be empty since there is no link text.  Ideally I'd like to display `[](http://example.com)`.  Bonus if the `http://exmaple.com` gets auto-linked (if enabled).

**Comment by skh-** [comment]
using remark-disable-tokenizers instead of `disallowedTypes` seems to solve this.

**Comment by marcoancona** [comment]
Hi @skh-,
we are facing the same issue. We would like to display the raw string from some of the markdown tags. I could not understand how to apply your suggestion of using the remark-disable-tokenizers instead of disallowedTypes... do you maybe have a code snippet to share, or some reference?

**Comment by skh-** [comment]
Sure, here's an example.

```tsx
import remarkDisableTokenizers from 'remark-disable-tokenizers';
import ReactMarkdown from 'react-markdown';

<ReactMarkdown
  plugins={[
    // ... list of plugins ..
    [[remarkDisableTokenizers, {
      block: ['definition'],
      inline: ['emphasis', 'deletion'],
    }]]
  ]}
/>
```

**Comment by marcoancona** [comment]
Thanks for the quick reply @skh- . What version of react-markdown are you using?
I get `Cannot read properties of undefined (reading 'inlineTokenizers')` when I try to use the `remark-disable-tokenizers` plugin. According to [this list](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins) the plugin is currently broken with the latest versions of remark.

**Comment by Nic0S** [comment]
I'm getting the same error, can this be reopened?

**Comment by ChristianMurphy** [comment]
@Nic0S there is no error in this issue.
There are questions and solutions around how the API work.
Being several years old, both the question and the answer apply to `react-markdown` version 5.

If you are using version 5, please see the solution in https://github.com/remarkjs/react-markdown/issues/387#issuecomment-1255340487

If you are using a different version, please open a new discussion (https://github.com/orgs/remarkjs/discussions) and offer a bit of context on what packages and versions of those packages you are using and what you want to achieve (https://github.com/remarkjs/.github/blob/main/support.md#asking-quality-questions)
