### ISSUE TITLE
Subscript and Superscript

### ISSUE THREAD

**Issue by mbrahimi617** [rexxars/react-markdown#388]
This is a nice package but I think you should include some plugins by default, especially so we can do:

    ^x^
    ~x~

We definitely need sub and sup plugin. People shouldn't have to know HTML tags for basic markdown.

**Comment by mbrahimi617** [comment]
I've tried to supply `remark-sub-super` to plugins with no luck. It's asking for a renderer and then crashes.

**Comment by Raicuparta** [comment]
Besides adding the `remark-sub-super` plugin, you need to also provide the renderers for `<sub>` and `<sup>` tags, which aren't included by default in react-markdown. Something like this:

```jsx
  <ReactMarkdown
    source="This is the 4^th^ time I've passed out in this club"
    plugins={[remarkSubSuper]}
    renderers={{
      sub: 'sub',
      sup: 'sup',
    }}
  />
```

**Comment by mbrahimi617** [comment]
Awesome, thank you!

**Comment by ankurpiparsania** [comment]
The way I solved this and other may find useful is as per below with use of components:

```
<ReactMarkdown remarkPlugins={[gfm]} children={props.content} 
components={{ 
      em: ({ node, ...props }) => { 
              if ( props.children[0] && typeof props.children[0] === 'string' && props.children[0].startsWith('^')) { 
                    return <sup>{props.children[0].substring(1)}</sup> 
               } 
              if ( props.children[0] && typeof props.children[0] === 'string' && props.children[0].startsWith('~')) { 
                    return <sub>{props.children[0].substring(1)}</sub> 
               } 
             return <i {...props} /> 
            },
 }}
```

with above code i can use ^® or ^th for superscripts and ~1 for subscripts.

hope above is useful.

**Comment by selvaganapathi5995** [comment]
> This is a nice package but I think you should include some plugins by default, especially so we can do:
> 
> ```
> ^x^
> ~x~
> ```
> 
> We definitely need sub and sup plugin. People shouldn't have to know HTML tags for basic markdown.

You can use unicode for sup and sub.
https://gist.github.com/molomby/9bc092e4a125f529ae362de7e46e8176

Example: ™ TRADE MARK SIGN (U+2122) => "ABC\u2122"

**Comment by AndrewGardhouse** [comment]
I've been using the [remark-supersub plugin](https://github.com/Symbitic/remark-plugins/blob/master/packages/remark-supersub/README.md), and it works right out of the box without any additional configuration

**Comment by kevalrathod** [comment]
"react-dom": "18.2.0",
    "react-markdown": "^8.0.7",
    "remark-gfm": "^3.0.1",
    "remark-sub-super": "1.0.20",
    
    sub and sup script is working in latest react-markdown.
    
```
<ReactMarkdown 
  className="text-base lg:text-lg react-markdown-content"
  children={delve(data, 'content')}
  plugins={[remarkGfm,remarkSubSuper]} 
  components={{
    sub: 'sub',
    sup: 'sup',
  }} 
/>
```
which still shows like this,
`Welcome to Gumlet^TM^`
