### ISSUE TITLE
Text defaulting to bold

### ISSUE THREAD

**Issue by negebauer** [rexxars/react-markdown#39]
I'm having a problem rendering some Markdown
What happens is that all the text is rendered as bold

For example, for this text
```
**This should be bold**

This shouldn't be bold
```

I'm seeing this render
<img width="1078" alt="captura de pantalla 2016-09-23 a las 21 11 20" src="https://cloud.githubusercontent.com/assets/11860880/18804515/4e2cd960-81d2-11e6-8274-ec099ef78c0f.png">

Any ideas of what might be happening?

This is the code where I render the markdown
```javascript
<Markdown source={body}/>
```
`body` is a string

**Comment by rexxars** [comment]
I expect this is styling unrelated to react-markdown - that a parent has `font-weight` set to `bold` or similar. 

Inspect the second paragraph in your browsers devtools and you should be able to tell what is applying the styles.
