### ISSUE TITLE
html-parser plugin not found

### ISSUE THREAD

**Issue by neilyoung** [rexxars/react-markdown#398]
```
const ReactMarkdown = require("react-markdown")
const htmlParser = require('react-markdown/plugins/html-parser')

```

Result:

```
Failed to rebuild.
./src/containers/Home.js
Module not found: Can't resolve 'react-markdown/plugins/html-parser' in '/Users/decades/Documents/dfja/dragonfly2/spa/src/containers'
```

Indeed. There is no such a plugin in the `plugins` subfolder. What?

**Comment by ChristianMurphy** [comment]
@neilyoung the file is included as part of the package, you can see it in npm here: https://unpkg.com/browse/react-markdown@4.3.1/plugins/

Can you ensure you have `react-markdown` installed?
Can you provide a more complete example of what you are trying?

**Comment by neilyoung** [comment]
Wow... I don't even remember to have had this problem. Can be closed :)
