### ISSUE TITLE
Enable escapeHTML by default

### ISSUE THREAD

**Issue by hiteshpatwari** [rexxars/react-markdown#40]
Please enable escapeHTML by default on the component, a Markdown component should always have escapedHTML.

**Comment by rexxars** [comment]
While I personally loathe HTML in Markdown, it is considered legal and "valid", and has fairly obvious use cases. From a quick glance, it doesn't look like other markdown renderers are escaping by default, either. I will however consider changing this default for the next major version.

**Comment by hiteshpatwari** [comment]
Thanks, This will be a much appreciated modification 👍

**Comment by rexxars** [comment]
The new release candidate for v3 escapes HTML by default. Please read [this issue](https://github.com/rexxars/react-markdown/issues/96) for more information. Please give it a go and let me know if you encounter issues.
