### ISSUE TITLE
plugins markdown-it-container does not work

### ISSUE THREAD

**Issue by pasBone** [rexxars/react-markdown#410]
```js
<ReactMarkdown
              source={'::: spoiler click me\n*content*\n:::\n'}
              plugins={[[require('markdown-it-container'), 'classname', {
                validate: name => name.trim().length,
                render: (tokens, idx) => {
                  if (tokens[idx].nesting === 1) {
                    return `<div class="${tokens[idx].info.trim()}">\n`;
                  } else {
                    return '</div>\n';
                  }
                }
              }]]}
            />
````
![image](https://user-images.githubusercontent.com/18027183/78471618-238bfb00-7765-11ea-8879-b6dcfe5fbe98.png)

TypeError: Cannot read property 'ruler' of undefined,
please help me...

**Comment by ChristianMurphy** [comment]
The plugins for `react-markdown` need to be [remark](https://github.com/remarkjs/remark) based.
There are quite a few https://github.com/remarkjs/remark/blob/master/doc/plugins.md

If you're interested in creating your own plugin, there is more info here: https://unifiedjs.com/learn
