### ISSUE TITLE
How to avoid <p> tag

### ISSUE THREAD

**Issue by amalajeyan** [rexxars/react-markdown#42]
Hello,
          There is a p tag always get enclosed when i use the markdown component which always disturbs my page layout. Can you please tell how to avoid that.

![image](https://cloud.githubusercontent.com/assets/23312382/20057205/53f52e0e-a510-11e6-9518-f56b489976a3.png)

**Comment by jordanmkoncz** [comment]
I was wondering this as well. It would be good if there was some way to avoid having the enclosing `<p>` tags.

**Comment by rexxars** [comment]
Sorry for not responding earlier, I've been a bit busy with life. You could set `Paragraph` as a `disallowedTypes` and set `unwrapDisallowed` to `true`. That'll make it a bit hard to handle newlines properly, though - not sure how you want to treat those? Example:

```jsx
<Markdown
    source="Normally, this *sentence* would be wrapped in a paragraph."
    disallowedTypes={['Paragraph']}
    unwrapDisallowed
/>
```

Or, you could just replace the renderer for paragraphs with something else:
```jsx
<Markdown
    source="Normally, this *sentence* would be wrapped in a paragraph."
    renderers={{Paragraph: 'span'}}
/>
```

This would render `<span>` instead of `<p>`, which might not be what you want, but you can use a custom react component instead if you want. Take a look at the readme for more information on the custom renderer feature.

**Comment by Fleuv** [comment]
This doesn't work in v4.0, please confirm.

**Comment by guillempuche** [comment]
You can also enable `unwrapDisallowed` to `true`.

My code:
`const markdownTypesAllowed = [
        'text',
        'strong',
        'delete',
        'emphasis',
        'link'
];`

`<Markdown
                    source={text}
                    allowedTypes={markdownTypesAllowed}
                    unwrapDisallowed={true}
/>`

**Comment by arisros** [comment]
> This doesn't work in v4.0, please confirm.
> 
> Seems like `Paragraph` got converted to lowercase `paragraph`. With the lowercase naming it does work.

  paragraph: 'p', 

with lowercase `p`

https://github.com/remarkjs/react-markdown/blob/634f88d610c3beb39411db5c928d2cfff440f9ff/src/renderers.js#L13

**Comment by vincerubinetti** [comment]
Note that as of 2021 (version ???), the parameter names have changed a bit:

```jsx
<ReactMarkdown
  components={{ p: "span" }}
  remarkPlugins={[remarkMath]}
  rehypePlugins={[rehypeKatex]}
>
  {children}
</ReactMarkdown>
```

**Comment by RemyMachado** [comment]
You can vanish the paragraph tag with a `React.Fragment`.

```typescript
  return (
    <ReactMarkdown
      components={{
        p: React.Fragment,
      }}
    >
      {children}
    </ReactMarkdown>
  )
```

**Comment by memben** [comment]
This worked for me & made my type checker happy
```tsx
<ReactMarkdown
  components={{
    p: ({ children }) => <>{children}</>,
  }}
>
  {content}
</ReactMarkdown>
```
