### ISSUE TITLE
Images consistently rendering inside <p> tags.

### ISSUE THREAD

**Issue by sam-cross** [rexxars/react-markdown#426]
`<img>` elements are rendering inside `<p>` tags, which is affecting my document flow. I'm using a custom renderer to wrap them inside a `<div>` (code below), but it's now wrapping *this* inside a `<p>` element too.

## React markup

```jsx
        <ReactMarkdown
                source={project.bodyMarkdown}
                escapeHtml={false}
                renderers={{
                    image: renderImage
                }} />
```

## renderImage

```jsx
    const renderImage = (props: any) => {
        return (
            <div className={"image-container"}>
                <img {...props} />
            </div>
        );
    }
```

## project.bodyMarkdown Example

```markdown
and designed this website you're viewing right now, over the span of two weeks.\n\n## Technologies\n\n![](https://source.unsplash.com/random/1920x1080)\n\nI love React, but I hate that it renders on the client
```

**Comment by ChristianMurphy** [comment]
@sam-cross that is how commonmark works, images are inline content, they get wrapped in a block (a paragraph).

If you want to change the behavior, use a plugin https://github.com/remarkjs/remark-unwrap-images

**Comment by sam-cross** [comment]
@ChristianMurphy Thanks for your response. I ended up using Marked and hacking together a solution from a related issue in that repo:

```jsx
import Marked from 'marked';

export default (
    body: string,
    imageContainerClassNames = ''
): string => {
    let renderer = new Marked.Renderer;
    renderer.paragraph = (text: string) => {
        if (text.startsWith('<img') && text.endsWith('>'))
            return `<div className="image-container ${imageContainerClassNames}">${text}</div>`;
        else
            return `<p>${text}</p>`
    }

    Marked.setOptions({
        xhtml: true,
        renderer
    });
    return Marked(body);
}
```

However, I think I might just switch back to react-markdown and leave images inside paragraphs after all, as it'll be easier for me to keep consistency in content widths.
