### ISSUE TITLE
special characters (square brackets) parsing issue

### ISSUE THREAD

**Issue by rjoydip** [rexxars/react-markdown#429]
Original issue https://github.com/denoland/deno_website2/issues/562

***Right:***
```markdown
status.code[code]
```
***Wrong:***
```markdown
status.codecode
```
Example: https://codesandbox.io/s/react-markdown-issue-with-square-brackets-36y0u

**Comment by ChristianMurphy** [comment]
@rjoydip this looks like it may be a bug in the parser, `remark-parse` you may want to report it upstream at https://github.com/remarkjs/remark/issues

**Comment by rjoydip** [comment]
@ChristianMurphy  Yup 👍
