### ISSUE TITLE
linkTarget option doesn't work

### ISSUE THREAD

**Issue by Vadorequest** [rexxars/react-markdown#438]
The following code doesn't generate a `a href="" target="_blank">` element. The target is basically missing from the generated output.

I wonder if it doesn't work, or if I've misused it somehow, it seems rather straightforward though.

```tsx
    <ReactMarkdown
      source={text}
      linkTarget={'_blank'}
    />
```

`text` value being
```
Super longue **description**

Vous pouvez même [utiliser des liens][1]

  [1]: https://bluebottlecoffee.com/releases/costa-rica-vista-al-valle-honey
```

**Comment by camro** [comment]
It seems to be that this is a linkReference, rather than a link.

**Comment by camro** [comment]
You can fix this with 
`renderers={{linkReference : props => <a href={props.href}`

So in your code
```
<ReactMarkdown
      source={text}
      renderers={{linkReference : props => <a href={props.href} target="_blank" rel="noopener">{props.children}</a>}}
    />
```

**Comment by Vadorequest** [comment]
Thanks, can't test it since I'm not using this lib anymore.
