### ISSUE TITLE
transformLinkUri not passing through uri parameter

### ISSUE THREAD

**Issue by WindfallProphet** [rexxars/react-markdown#453]
markdownEx = ` [example.com](https://example.com) `

... <Markdown source=markdownEx  transformLinkUri={ ({uri}) => { ... } />

Maybe I'm not doing this correctly, but I'm not able to access the uri parameter so I can manipulate it. I can return a different value (ex. ` return "github.com" ), but I want to return a value conditional to the original.

**Comment by gilisho** [comment]
I think your code should be:
```
<Markdown source=markdownEx transformLinkUri={ (uri) => { ... } />
```

The parameter to the `transformLinkUri` function is not an object, but the href itself if I'm not wrong.

**Comment by WindfallProphet** [comment]
This works, thank you.
