### ISSUE TITLE
How to get syntax highlight support?

### ISSUE THREAD

**Issue by shoumma** [rexxars/react-markdown#46]
Currently it shows a plain code block without any syntax highlighting. Could you please tell me how can I add a syntax highlighting support to it?

**Comment by rexxars** [comment]
You can use a custom renderer for `CodeBlock` type.

There are some examples over here: https://github.com/rexxars/react-markdown-examples
Specifically, the [code renderer](https://github.com/rexxars/react-markdown-examples/blob/master/examples/custom-renderers/code-renderer.js).

It's totally up to you -  the demo in this repo uses a simpler but less efficient way to highlight code, using highlight js. Source here: https://github.com/rexxars/react-markdown/blob/master/demo/src/code-block.js
