### ISSUE TITLE
how to import a *.md file in react project

### ISSUE THREAD

**Issue by liule1988** [rexxars/react-markdown#47]
I want to use markdown in my Github Pages with react ,but I met this error -- "Cannot find module "../../test.md",can you give me some suggest.thank you!

**Comment by rexxars** [comment]
You would have to load the markdown to a string somehow. If you're using webpack, you can use [raw-loader](https://github.com/webpack/raw-loader). 

For a client side solution, you could load the markdown using  the [fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) or XMLHttpRequest. 

Either way, this isn't really within the scope of react-markdown - its up to the application to get hold of the markdown.
