### ISSUE TITLE
How to make editor panel and result panel scrolling at the same time?

### ISSUE THREAD

**Issue by jettangs** [rexxars/react-markdown#50]
Need some tips, thx.

**Comment by rexxars** [comment]
Ehm. If you just want them to be 1:1 pixel-wise, then it shouldn't be harder than a couple of scroll listeners and some `element.scrollTo()` calls.

If you want the result pane to follow the *content*, that's will be slightly harder. I guess you might be able to make something work by setting `sourcePos` to true, then on input event figure out which line number the cursor is on and scroll to the first rendered element that has a source position which starts on that line?

This isn't really all that related to react-markdown as there are no "editor" and "result panel" concepts built in, but hopefully this will give you some ideas to start with.

**Comment by jettangs** [comment]
Thanks for your suggest, I know how to do now.
