### ISSUE TITLE
Impor tMarkdown file

### ISSUE THREAD

**Issue by Kcin1993** [rexxars/react-markdown#52]
I import a .md file so that I can focus the markdown content in a single file.
But the console show： `Module not found: ./components/MdContent.md`

My code is something like this.
```
import React, { Component } from 'react';
import './../App.scss';
import MdContent from './components/MdContent.md';
var ReactMarkdown = require('react-markdown');
var input = {MdContent};

class YosgoMarkDown extends Component {

    render() {
        return(
            <div className="YosgoMarkDown">
                <ReactMarkdown source={input} />
            </div>
        );
    }
}
export default YosgoMarkDown;
```

I use create-react-app and my folder structure is like this
src
⎿ App.js
⎿ index.js
⎿ components
  ---⎿ YosgoMarkDown.js
  ---⎿ MdContent.md

Is there any wrong or some other advice to import a .md file?

**Comment by rexxars** [comment]
This isn't really a question that is related to this module. Importing markdown files like you do above would require something like [raw-loader](https://github.com/webpack/raw-loader), which isn't included in create-react-app.

How you get hold of the content that react-markdown is to render is too wide a topic to cover here - you could import it using raw-loader, you could fetch it using an XMLHttpRequest, you could just have it as a plain old string. If you're server-rendering, you could use `fs` to read the file.

Sorry I can't be of more help - I would have given you instructions on how to use raw-loader with create-react-app, but it seems the authors of that project do not want people to edit the webpack configuration, and as such it's hard to do much about it.

**Comment by Kcin1993** [comment]
I appreciate your reply! Thanks above information to help me create good application!
