### ISSUE TITLE
Detect consecutive images

### ISSUE THREAD

**Issue by moimael** [rexxars/react-markdown#54]
Hi,

Is there any way to detect consecutive images with react-markdown ?

Use case is, we write articles in markdown and want to provide a generic layout for images depending on the number of consecutive images.

For example: 
1 image: full-width
2 images: side-by-side
3 images: 2 side-by-side and 1 full size underneath
4 images+: a gallery component

Thanks !

**Comment by rexxars** [comment]
There is an undocumented `walker` property, which is a function that can be used to do *some* manipulation. *Please* be aware however that I intend to remove/replace it in an upcoming update, as the new parser will work slightly differently - so be careful putting too much logic into it.

I'm working on a full rewrite based on a new parser. This will open new ways to interact with the [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree), and should allow for this sort of thing more easily.
