### ISSUE TITLE
Support for unescaped newlines

### ISSUE THREAD

**Issue by jeremyblalock** [rexxars/react-markdown#56]
We are migrating our web app from Backbone to React, and hoping to replace [marked](https://github.com/chjj/marked) with react-markedown. The problem it, we need to convert single newlines to broken newlines (`<br />`), and I can't seem to find a way to do that in react-markdown.

This is the option we set in [marked]() to enable this functionality: https://github.com/chjj/marked#breaks

We need this support for backwards compatibility in our app, as well as to follow the generally accepted Github style of markdown which is fairly well known to our users. From what I can tell, because react-markdown uses [CommonMark](https://github.com/jgm/CommonMark), this is not something available as an option. 

Any thoughts?

**Comment by prog8** [comment]
I also have similar problem. It's not convenient to use `<br/>` in each place I want to break line.

**Comment by johnandblue** [comment]
Have you tried use `Hardbreak` as prop? I had a similar issue  using `Softbreak` as the <p> that creates comes with a `margin-top` and `margin-bottom`

**Comment by rexxars** [comment]
This has changed a bit since v3 was released. Please see https://github.com/rexxars/react-markdown/issues/105#issuecomment-346103734
