### ISSUE TITLE
Problem While Using Webpack 2

### ISSUE THREAD

**Issue by nickroberts404** [rexxars/react-markdown#57]
Webpack will successfully bundle my code that includes react-markdown, but during runtime I get this error: 

`Uncaught Error: Cannot find module "../maps/xml.json"`

The module it's referring to is `require`'d in [commonmark](https://www.npmjs.com/package/commonmark), but I suspect this is an issue many of you may have had/solved and I'm just blanking on a way around it. Any suggestions? 
Thanks!

Here is my very basic webpack.config, 
```
var config = {
	entry: './src/js/main.js',
	output: {
		filename: 'bundle.js',
		path: __dirname + '/src',
	},
	module: {
		rules: [
			{
				test: /\.jsx?$/,
				use: ['babel-loader'],
				include: __dirname + '/src/js',
			},
		]
	}
}
```

**Comment by kennetpostigo** [comment]
I'm using this within webpack 2, but I don't get this error.

**Comment by nickroberts404** [comment]
I just checked back on this, updated everything and it works fine. Not sure what was going on then, it could have been the way I was serving the file locally. Thanks for getting back!
