### ISSUE TITLE
Too strict TS typings

### ISSUE THREAD

**Issue by Pajn** [rexxars/react-markdown#59]
The renderers prop is typed as `readonly renderers?: {[nodeType: string]: Component<any, any>};`
however `Component` only allows class component, not functional components. 

The react typings does instead export a type named `ReactType` that can be used for all components. So the renderers prop should be typed as  `readonly renderers?: {[nodeType: string]: ReactType};`

**Comment by rexxars** [comment]
Thanks for reporting. I don't use TS myself, so it's hard for me to stay on top of this. Could you send a pull request?

**Comment by Pajn** [comment]
Sure, done
