### ISSUE TITLE
Injecting of several custom React components in markdown string

### ISSUE THREAD

**Issue by sashakirichek** [rexxars/react-markdown#64]
Is it possible to inject array of React components inside of one markdown string?
For example: we have one localized string that contains full article and need to render custom react components in the middle.
I have tried to use image title in renderer to be able to distinguish what component should I return: 

```
imagesRenderer = (props, src, components) => {
    const key = props.title;
    if (key) {
      return components[key]();
    }    

    return (<ImageWithCheck src={src} alt={props.alt}/>);
  };

render() {
    return (<Markdown source={this.props.text} 
        renderers={{Link: this.routerLink, Image: (props) => this.imagesRenderer(props, props.src.match(/^(https?:)?\/\//) ? props.src : Utils.getImageUrl(props.src), this.props.components)}}/>);
  }
```

So here I render usual image in case there is no title defined:
`![alt text](image.png)`

And if title exists I am rendering corespondent react component from "components" array.

Is there any way to do it better?
Thanks

**Comment by rexxars** [comment]
I'm sorry, I just don't understand what you're trying to achieve...
From the example, it looks like you're trying to render different components based on props, which is obviously feasible, but you'll be limited by the information you have available, yes.

From the text in the issue, you're asking if it's possible to inject an *array* of components, but I'm not sure what that means... From a single renderer? In this case, you'd have to wrap it in a parent, as React only allows returning a single element (for now).
