### ISSUE TITLE
Opening link in a new tab

### ISSUE THREAD

**Issue by gavin-johnson84** [rexxars/react-markdown#65]
Is it possible to add `target="blank"` to Markdown links?

For example I wish to have the following URL open in a new browser tab when I left click:
`[link to website](http://www.website.com)`

Cheers

**Comment by rexxars** [comment]
You can use a custom renderer:

```js
function LinkRenderer(props) {
  return <a href={props.href} target="_blank">{props.children}</a>
}

<ReactMarkdown
  source="Click [here](https://espen.codes/) to visit external site"
  renderers={{Link: LinkRenderer}}
/>
```

**Comment by Dictory** [comment]
@rexxars `renderers={{Link: LinkRenderer}}` is incorrect, `Link:` => `link:` to lowercase =)

**Comment by abourget** [comment]
it works here with the capital `L` in `Links:`

**Comment by chenop** [comment]
I'm re-opening to suggest a syntax that opens a link in a new tab:
[link](url){:target="_blank"} 

Is this feature make sense? 
I'm willing to give it a try implementing this.

**Comment by joelbowen** [comment]
For anyone else that ends up here via google search (like I did) and didn't notice this in the docs, you can now use the `props` to achieve this like so:

```jsx
<ReactMarkdown linkTarget="_blank" children={...} />
```

See [the docs](https://github.com/remarkjs/react-markdown#props) for more info.

**Comment by phongapp** [comment]
> For anyone else that ends up here via google search (like I did) and didn't notice this in the docs, you can now use the `prop` `linkTarget` to achieve this like so:
> 
> ```js
> <ReactMarkdown linkTarget="_blank" children={...} />
> ```
> 
> See [the docs](https://github.com/remarkjs/react-markdown#props) for more info.

Does React Markdown automatically add `rel=”noopener noreferrer”` when using `linkTarget="_blank"` for secure?

**Comment by ChristianMurphy** [comment]
This answer is pretty outdated, and should no longer be used as a reference.
The current recommendation is to use https://github.com/rehypejs/rehype-external-links which can apply `rel`.

I'm locking this thread as outdated.
Feel free to take follow up questions to the discussion forum https://github.com/orgs/remarkjs/discussions
