### ISSUE TITLE
I found the simple method to solve the code hightlight !

### ISSUE THREAD

**Issue by ycjcl868** [rexxars/react-markdown#68]
Download the prism.js css or hightlight.js css 
![image](https://cloud.githubusercontent.com/assets/13595509/24318482/2333961e-1141-11e7-89df-e26288fbaeab.png)

and the configure with the webpack (resolve.alias)
![image](https://cloud.githubusercontent.com/assets/13595509/24318490/45cef236-1141-11e7-85b1-35af509e66b9.png)

to import the alias

![image](https://cloud.githubusercontent.com/assets/13595509/24318538/df544d02-1141-11e7-80cd-47a5a3e600eb.png)

Finally, I  works,

![image](https://cloud.githubusercontent.com/assets/13595509/24318541/f04fa62e-1141-11e7-95e6-4be29d99b08c.png)

**Comment by rexxars** [comment]
Thanks for the guide! Added a reference label so I (and others) can find this easier in the future.

**Comment by yuqingc** [comment]
:+1:
