### ISSUE TITLE
Add new prop `sourceFile`

### ISSUE THREAD

**Issue by bogas04** [rexxars/react-markdown#7]
Usually markdown files are read from fs so I think having sourceFile will just make it easier to use it.

Something on similar lines:

```js
require('fs')
.readFileSync(this.props.sourceFile, this.props.sourceFileEncoding || 'utf8', (err, file) => {
  this.setState({ source: file });
});
```

**Comment by rexxars** [comment]
Thanks for the interest!

I'm not sure I agree that this is the usual case... I've mainly used this in the browser. I think this is trivial to do outside the component:

```js
var fs = require('fs');
var ReactDOM = require('react-dom/server');
var sourceFile = 'path/to/file.md';

ReactDOM.renderToString(
    <Markdown source={fs.readFileSync(sourceFile, 'utf8')} />
);
```

**Comment by jjstrat3** [comment]
@bogas04 If you're using Webpack, you might try this:

##### Add the [raw-loader](https://github.com/webpack/raw-loader) to your webpack config:
```
{
    module: {
        loaders: [
        // ....other loaders
        , {
            test: /\.md$/,
            loader: 'raw'
        }]
    }
}
```

##### Then, optionally, add the `.md` extension to your config's resolve property:
```
resolve: {
  extensions, [/*...other file exts */ , '.md'],
}
```

##### Finally, just add the file as an import in your React component:
```
import React from 'react';
import ReactMarkdown from 'react-markdown';
import myMdFile from 'docs/myMdFile';

class Docs extends React.Component {
  render() {
    return (
      <ReactMarkdown source={myMdFile} />
    );
 }
```

**Comment by Dico200** [comment]
Can I reference a URL instead of a file as well? Like you can do with images, `src=/img.png` on a website
