### ISSUE TITLE
Empty space before closing tag breaks rendering

### ISSUE THREAD

**Issue by bernd-protofy** [rexxars/react-markdown#72]
Hi there,

if i have a markdown like **bold ** with a space before the "closing" ** the markdown is not beeing rendered. Do you have a solution for that?

Regards,
Bernd

**Comment by rexxars** [comment]
Not really, this is the way most markdown parsers work, including here on **GitHub **.
Changing this could cause unwanted rendering for a lot of people, so I'm going to close this.

You could always try to solve it using regular expressions;
```js
const input = 'Bold text is neat, **especially ** with markdown.'
const fixed = input.replace(/\*\*\s*(.*?)\s*\*\*/g, '**$1**')
```

**Comment by bernd-protofy** [comment]
Ok. Thx
