### ISSUE TITLE
Is `react-markdown` compatible with browser?

### ISSUE THREAD

**Issue by maruilian11** [rexxars/react-markdown#73]
I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently we want to host your popular lib on https://cdnjs.com. I need to confirm if it can directly use in browser? Thank you!

https://github.com/cdnjs/cdnjs/pull/11137

**Comment by rexxars** [comment]
If you use the UMD bundle, it's possible to use it in the browser, but it requires that React is loaded on the same page first.

I have not checked in the UMD bundle to source control - but it's available in the NPM package; https://unpkg.com/react-markdown@2.5.0/umd/react-markdown.js

I can't see it working out of the box as the pull request stands, but I could potentially check in the UMD bundle(s) if that helps?

**Comment by maruilian11** [comment]
@PeterDaveHello If this lib need React to be loaded first, can we host the UMD bundle? Thanks!

**Comment by PeterDaveHello** [comment]
I didn't see a problem here, can't we just use its umd release on npm?

**Comment by maruilian11** [comment]
Thanks, we will turn to use `umd` on npm.
