### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by exinferis** [rexxars/react-markdown#75]
How can we deal with possible broken markdown documents - so if the markdown code is not valid or the document (in out case retrieved via an api) cannot be loaded. Are there any validation, error etc events?

**Comment by rexxars** [comment]
What constitutes as invalid markdown?
Markdown is extremely "loose" - anything you might consider "invalid" is just treated as text. For instance, if you start a line with `--` and was expecting that to be turned into a horizontal rule, there really isn't any way for the parser to know that. It just treats it as two dashes.

**Comment by rexxars** [comment]
Closing this since I didn't get any clarification.
