### ISSUE TITLE
Including external .md files

### ISSUE THREAD

**Issue by russellbits** [rexxars/react-markdown#76]
I have tried to include static markdown files, but all this module appears to do is present the file reference rather than the content of the file. For instance,

    import React from 'react';
    import ReactDOM from 'react-dom';
    import ReactMarkdown from 'react-markdown'

    const content = require('./content/thinstyle.md')

    ReactDOM.render(
      <ReactMarkdown source={content} />,
      document.getElementById('root')
    );

Is there some other method in this situation to stream the contents of the file. I'm not aware of any other include methods in Javascript.

**Comment by russellbits** [comment]
Incidentally, I've discovered the FileReader npm package, but all the examples of using it involve dealing with a file interactively uploaded to a web page (through a form) not locally loading the file.

**Comment by russellbits** [comment]
Weirdly, the fs package doesn't help at all either. When I do this:

    import content from './content/thinstyle.md'

    fs.readFile(content, (err, data) => {
      if (err) throw err;
      console.log(data);
    });

Webpack throws an error that essentailly says that readFile is not a function.

**Comment by russellbits** [comment]
Ok. I see what I'm doing wrong. The markdown doesn't get compiled into the production bundle the way I thought. I thought there was a way to compile the markdown into the javascript bundle. Is that possible? If not, I guess this has to be an ajax call.

**Comment by rexxars** [comment]
You can use [raw-loader](https://github.com/webpack-contrib/raw-loader) to convert a markdown file to a string. 

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.md$/,
        use: 'raw-loader'
      }
    ]
  }
}
```

**Comment by russellbits** [comment]
Hey, thanks! I know that wasn't exactly an issue with react-markdown, so thanks for the hint!

**Comment by rexxars** [comment]
Happy to help ☺️

**Comment by zhanglinge** [comment]
This probs trouble me a lot, may I know what's your solution eventually? Did you use any other package?

**Comment by wellenzhong** [comment]
@zhanglinge 
I use the 'file-loader' instead.
1.  install the file-loader and config your webpack.config.js file;
2. import your .md file to your page;now,you can get the .md file path;
3. fetch your .md file and get the content of your .md file.


`
const content = require('../assets/doc/agreement.md')
....
   componentDidMount() {
        fetch(content).then(response => {
            return response.text()
        }).then(text => {
            console.log(text)
            this.setState({
                agreementContent: text
            })
        }).catch(err => {
            console.log(err)
        })
}
`
you can also get for help from here:https://stackoverflow.com/questions/42928530/how-do-i-load-a-markdown-file-into-a-react-component

**Comment by zhanglinge** [comment]
@wellenzhong I see, many thanks.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Is it possible to fetch markdown files from github repo's into my react website?

**Comment by Beamanator** [comment]
> Is it possible to fetch markdown files from github repo's into my react website?

I successfully got this running in my functional component, hope it helps!

```javascript
const [mdText, setMdText] = useState('');

useEffect(() => {
        fetch("https://raw.githubusercontent.com/Beamanator/fdi/master/README.md")
            .then((response) => {
                if (response.ok) return response.text();
                else return Promise.reject("Didn't fetch text correctly");
            })
            .then((text) => {
                setMdText(text);
            })
            .catch((error) => console.error(error));
    });
```
