### ISSUE TITLE
Markdown component rendered after siblings?

### ISSUE THREAD

**Issue by jchook** [rexxars/react-markdown#77]
It appears that the actual rendering of markdown happens AFTER everything else has been rendered. This is a huge annoyance for integrating markdown with anything else on the page.

Here is some pseudo-code to help you understand what I'm talking about:

```javascript
const React = require('react');
const ReactDOM = require('react-dom');
const ReactMarkdown = require('react-markdown');

function MyComponent(props) {
  let stepNumber = 0;

  const source = `# Alpha
  # Beta
  # Gamma
  # Delta`;

  const markdownRenderers = {
    Heading: ({ level, children }) => {
      stepNumber += 1;
      return (
        <h1>{stepNumber}. {children}</h1>
      );
    }
  };

  return (
    <h1>{stepNumber += 1}. Hello world</h1>
    <ReactMarkdown source={props.source} renderers={markdownRenderers} />
    <h1>{stepNumber += 1}. Goodbye world</h1>
  );
}

ReactDOM.render(
  <MyComponent source={source} />,
  document.getElementsByTagName('main')[0]
);
```

The output of this is essentially:

```html
<h1>1. Hello world</h1>
<h1>3. Alpha</h1>
<h1>4. Beta</h1>
<h1>5. Gamma</h1>
<h1>6. Delta</h1>
<h1>2. Goodbye world</h1>
```

Maybe we need to add a "prerender" flag/prop to the ReactMarkdown component?

So far the only solution I have is to use CSS counters... but I can imagine countless other scenarios where a more natural render order would be both expected and required.

**Comment by rexxars** [comment]
This is kind of the way React works though, isn't it?

I'm going to release a new beta soon that will expose the AST a little easier. This scenario really should be done as part of the data and not the rendering, in my opinion.

**Comment by jchook** [comment]
Wow I think you are right. Strange!

I made [a thing to test your hypothesis](http://cloud.jchook.com/1l3c1x2O260X) and it seems that my problem is indeed stemming from the render order of React itself.

Thanks for the response.
