### ISSUE TITLE
support bind react-router-dom Link element to <a>

### ISSUE THREAD

**Issue by zhenyulin** [rexxars/react-markdown#79]
I may get the documentation wrong, but currently it doesn't seem possible to bind the Link element to links to ensure non-refresh behaviour, would be great to have that.

**Comment by rexxars** [comment]
Just use a custom renderer for the Link type. See #29

**Comment by zhenyulin** [comment]
@rexxars works well, thanks!

Think it would be nice to support that more natively ; )
