### ISSUE TITLE
backtick marked string linebreak parse inssue

### ISSUE THREAD

**Issue by zhenyulin** [rexxars/react-markdown#80]
```
const source = `### this is a title
 this is a paragraph`
<ReactMarkdown source={source} />
```

this will output 

### this is a title
```
this is a paragraph
```

**Comment by rexxars** [comment]
Don't understand what the problem is?

If I paste
```
### this is a title
this is a paragraph
```
into http://rexxars.github.io/react-markdown/

It renders just like it is supposed to - H3, paragraph. What are you expecting?

**Comment by zhenyulin** [comment]
Hi @rexxars , I got the problem when using the backtick template literals in ES6 as shown in the code part, the H3 title output is OK, but the paragraph after the breakline is automatically wrapped in code block for some reason, for which I'm expecting normal text

**Comment by rexxars** [comment]
This is because the paragraph inside the template literals is indented. In markdown, leading whitespace means code.
