### ISSUE TITLE
Invalid type when using ReactMarkdown

### ISSUE THREAD

**Issue by CBarraford** [rexxars/react-markdown#81]
I've been banging my head on this, I don't know what I'm doing wrong. For some reason, the following code generates the following error for me.
```
<ReactMarkdown source="hello" />
```
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AchievementCard`.
```

Removing `ReactMarkdown` does fix it. I am using `react-router-dom` with the latest `react-markdown` (2.5.0).

**Comment by rexxars** [comment]
How does you require/import statement look?

**Comment by CBarraford** [comment]
I figured it out, i was importing `ReactMarkdown` incorrectly in es6.

WRONG
```
import { ReactMarkdown } from 'react-markdown'
```
Corrrect
```
import ReactMarkdown from 'react-markdown`
```
