### ISSUE TITLE
 question : highlight is use highlight.js ?

### ISSUE THREAD

**Issue by lijinke666** [rexxars/react-markdown#83]
i use `react-markdown` in my project
The generated code block is not highlighted
How can I use it
I find the examples you provided has  like `hljs-keyword` className

**Comment by rexxars** [comment]
You can use whatever syntax highlighting you want, you just need to provide the glue with a custom renderer. You could for instance use [react-lowlight](https://github.com/rexxars/react-lowlight).

Here's an example of how to do that: https://github.com/rexxars/react-markdown-examples/blob/master/examples/custom-renderers/code-renderer.js

If you want to use prismjs, here's some info on that: https://github.com/rexxars/react-markdown/issues/58
