### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by kennetpostigo** [rexxars/react-markdown#86]
Hey,

I want to swap out the header component for my own, but I see all heading are grouped under:
`Heading - (h1, h2, etc.)`

Is there a way to only swap out specific headings like only h1? because it overrides the other heading elements.

**Comment by rexxars** [comment]
Default renderers are exposed on `.renderers`, so you should be able to do (untested):

```js
const Markdown = require('react-markdown');

function HeadingRenderer(props) {
  if (props.level === 1) {
    return <h1>{props.children}</h1>
  }

  const Heading = Markdown.renderers.Heading
  return <Heading {...props} />
}

<Markdown
  source="# Some heading!\n\nAnd a paragraph"
  renderers={{Heading: HeadingRenderer}}
/>
```

**Comment by cpBurn** [comment]
Got it working with `const Heading = Markdown.renderers.heading` instead of `const Heading = Markdown.renderers.Heading` (lower case H).

**Comment by Kuboczoch** [comment]
I recently got it working with:
`renderers={{ heading: HeadingRenderer }}` lower case H in `heading` and also with `Markdown.renderers.heading`

Basically all thing are now in lower case

**Comment by abcd-ca** [comment]
Here's an adjustment to @rexxars' version that covers all header levels dynamically:

```tsx
<ReactMarkdown
  source={source}
  renderers={{
    heading: ({ children, level }) => {
      return (
        <Typography variant={`h${level}` as any}>
          {children}
        </Typography>
      )
    },
    paragraph: Typography
  }}
/>
```

(The ` as any` part is for Typescript only)

**Comment by daveteu** [comment]
> 
<img width="884" alt="image" src="https://github.com/remarkjs/react-markdown/assets/18649392/bff56777-88d8-4fc7-9f41-c70dcd279853">
How do we resolve this?

**Comment by wooorm** [comment]
This issue was closed 6 years ago. Open new issues.

Everything discussed here is out of date: read the readme on what you have to do.
