### ISSUE TITLE
String literal with link references not resolved

### ISSUE THREAD

**Issue by pke** [rexxars/react-markdown#89]
I have a string literal:

```
`[link] https://www.google.com

[Link][link] to google.
`
```

When using this a a `source` in my app using `2.5.0` of react-markdown the link ref is printed verbatim instead of being resolved. Moving the link ref definition to the end of the file also does not help.

**Comment by depadiernos** [comment]
Looks like the same issue as https://github.com/rexxars/react-markdown/issues/91.

**Comment by rexxars** [comment]
Is this even valid markdown? I can't seem to get any other markdown parsers to render this, either?

**Comment by pke** [comment]
It's described here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

Or am I missreading the docs?

**Comment by rexxars** [comment]
Should be something like this:

```
[Link to Google][some-identifier]

[some-identifier]: https://www.google.com
```

**Comment by rexxars** [comment]
Well, the only problem with your example is the missing `:` after `[link]` in the first line :)
