### ISSUE TITLE
Support auto link creation

### ISSUE THREAD

**Issue by pke** [rexxars/react-markdown#90]
Would be nice if the component would auto detect links and and emails and convert them to `<a>`.

**Comment by bionikspoon** [comment]
This would be a great feature.  In the meantime I have a snippet to share:

```js
const formatLinks = source => {
  const reUrl = /([^\[\(])(https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}[-a-zA-Z0-9@:%_\+.~#?&//=]*)([^\]\)])/g
  return source.replace(reUrl, '$1[$2]($2)$3')
}

export default function Story(props) {
  return (
    <ReactMarkdown
      className="markdown-body"
      source={formatLinks(props.data.story.description)}
    />
  )
}
```
Borrowed & modified the url regex from https://stackoverflow.com/a/3809435.  Added checks to make sure the url isnt inside brackets or parenthesis.

**Comment by rexxars** [comment]
The new release candidate for v3 automatically creates links by default. Please read [this issue](https://github.com/rexxars/react-markdown/issues/96) for more information. Please give it a go and let me know if you encounter issues.

**Comment by rsslldnphy** [comment]
For anyone who finds this in future, the way to do this has now changed, and you need to include a plugin: https://github.com/remarkjs/react-markdown#use

```typescript
import React from 'react'
import ReactDom from 'react-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

const markdown = `Just a link: https://reactjs.com.`

ReactDom.render(
  <ReactMarkdown children={markdown} remarkPlugins={[remarkGfm]} />,
  document.body
)
```

(Easy enough to find in the docs but google turns up this issue first)

**Comment by AnilSonix** [comment]
Ca anyone share any lib or similar snippet to auto link emails ?

**Comment by wooorm** [comment]
Locking, this is an ancient issue. Open questions if you have questions.

Furthermore, see the comment above your comment...
