### ISSUE TITLE
How to build automatic table of contents?

### ISSUE THREAD

**Issue by astranavt** [rexxars/react-markdown#92]
Is there a possibility of automatic generation of header?

**Comment by joshkadis** [comment]
I did this using a custom renderer for the `root` element:

```
    root: ({ children }) => {
      const TOCLines = children.reduce((acc, { key, props }) => {
        // Skip non-headings
        if (key.indexOf('heading') !== 0) {
          return acc;
        }

        // Indent by two spaces per heading level after h1
        let indent = '';
        for (let idx = 1; idx < props.level; idx++) {
          indent = `${indent}  `;
        }

        // Append line to TOC
        // This is where you'd add a link using Markdown syntax if you wanted
        return acc.concat([`${indent}* ${props.children}`]);
      }, []);

      return (
        <div>
          <Markdown source={TOCLines.join("\n")} />
          {children}
        </div>
      );
    },
```

Basically it...

1. Loops through the rendered child components of the `<Markdown />` component
1. Turns the headings back into Markdown
1. Renders that using a nested `<Markdown />` component

Seems to work!

**Comment by piwysocki** [comment]
Do you have an idea how to do it in latest version where root is removed?

**Comment by Murderlon** [comment]
Take a look at [`remark-toc`](https://github.com/remarkjs/remark-toc/).

**Comment by piwysocki** [comment]
OK, but I'm asking if it's possible in latest version to loop through the rendered child components of the <Markdown /> component

**Comment by Murderlon** [comment]
I don't understand why you want to implement this naive code compared to a well tested plugin to generate a table of contents.

> OK, but I'm asking if it's possible in latest version to loop through the rendered child components of the Markdown component.

Not with `root`, instead you do it per type: https://github.com/remarkjs/react-markdown#appendix-b-components
