### ISSUE TITLE
Errors out on compilation with Webpack 3.8.1

### ISSUE THREAD

**Issue by ChrisW-B** [rexxars/react-markdown#95]
When trying to build for production, throws the error
```
ERROR in app.js from UglifyJs
Unexpected character '�'
```
(Using babel 7, react-markdown 2.5.0)

**Comment by rexxars** [comment]
Don't think this is related to react-markdown... 
See the following gist: https://gist.github.com/rexxars/6168e5d41f770e929d900e88e5f743b4

```
espenh@ambrose:~/webdev/wp-test$ npm run build

> wp-test@1.0.0 build /home/espenh/webdev/wp-test
> webpack

Hash: 8ed1194b25cf8081f648
Version: webpack 3.8.1
Time: 2055ms
 Asset    Size  Chunks             Chunk Names
out.js  191 kB       0  [emitted]  main
   [9] ./index.js 296 bytes {0} [built]
    + 45 hidden modules
```

If you have more details that can show the error is somewhere in react-markdown, let me know.

**Comment by ChrisW-B** [comment]
Unfortunately webpack didn't give me a great amount of info on where the error came from, other than `app:29305,59`. I can tell you that switching to react-remarkable fixed it, and that when I tried to search through node_modules for � , commonmark and react-markdown came up. 

Since its working for you I'm going to assume it's an issue with case sensitivity or something else weird.

Sorry I couldn't be of more help, and thanks for taking the time to check this out!
