### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by cbroberg** [rexxars/react-markdown#97]
I can't figure out how to code what you actually do in your example at http://rexxars.github.io/react-markdown/

When i put ```js string literals into the input all i get is VS Code parsing errors. Do you have a more elaborate example than just const input = "# This is a header\n\nAnd this is a paragraph\n\n" ? More in the directions of your mentioned example?

Thanks in advance

**Comment by rexxars** [comment]
You have to be careful to escape the backticks (`` ` ``) when you put it into code, with a leading slash, like this: `` \` ``. Here's an example this might illustrate this better;

```js
const React = require('react')
const ReactDOM = require('react-dom')
const ReactMarkdown = require('react-markdown')

const input = `
# This is a header

And this is a paragraph

Code sample:

\`\`\`js
this is a code sample
\`\`\`

How's that?
`

ReactDOM.render(
    <ReactMarkdown source={input} />,
    document.getElementById('container')
)
```

I'd like to point out that this has nothing to do with this library, but rather just [ES6 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and the (unfortunate?) choice of markdown using the same backtick operator for code.

**Comment by rexxars** [comment]
Let me know if you need any more help. Closing for now.
