### ISSUE TITLE
support for the following syntax

### ISSUE THREAD

**Issue by omryr** [rexxars/react-markdown#98]
if i wanted to add support for syntax like: 
## Tables

// | Option | Description |
// | ------ | ----------- |
// | data   | path to data files to supply the data that will be passed into templates. |
// | engine | engine to be used for processing templates. Handlebars is the default. |
// | ext    | extension to be used for dest files. |

Right aligned columns

// | Option | Description |
// | ------:| -----------:|
// | data   | path to data files to supply the data that will be passed into templates. |
// | engine | engine to be used for processing templates. Handlebars is the default. |
// | ext    | extension to be used for dest files. |
 
or 

## Blockquotes

// > Blockquotes can also be nested...
// >> ...by using additional greater-than signs right next to each other...
// > > > ...or with spaces between arrows.

would there be a way to add support for this with the library somehow?  at the moment these syntaxes dont work for me at all, any help would be much appericiated!

**Comment by rexxars** [comment]
Tables and nested blockquotes are supported as of v3.0.0, which was released yesterday.
